"use client";

import {
  AddRegular,
  AddSquareRegular,
  AlertRegular,
  ArchiveRegular,
  ArrowClockwiseRegular,
  ArrowDownloadRegular,
  ArrowDownRegular,
  ArrowLeftRegular,
  ArrowRightRegular,
  ArrowRotateClockwiseRegular,
  ArrowTrendingRegular,
  ArrowUploadRegular,
  ArrowUpRegular,
  ArrowUpRightRegular,
  AttachRegular,
  BluetoothRegular,
  BoardRegular,
  BookmarkRegular,
  BookRegular,
  BotRegular,
  BranchRegular,
  BuildingRegular,
  CalculatorRegular,
  CalendarRegular,
  CameraRegular,
  CartRegular,
  ChartMultipleRegular,
  ChatRegular,
  CheckmarkCircleRegular,
  CheckmarkRegular,
  CheckmarkStarburstRegular,
  ChevronDownRegular,
  ChevronLeftRegular,
  ChevronRightRegular,
  ChevronUpDownRegular,
  ChevronUpRegular,
  CircleHintRegular,
  CircleRegular,
  ClipboardPasteRegular,
  ClipboardRegular,
  ClockRegular,
  CloudRegular,
  CodeRegular,
  ColorRegular,
  CopyRegular,
  CutRegular,
  DatabaseRegular,
  DataLineRegular,
  DataPieRegular,
  DeleteRegular,
  DesktopRegular,
  DismissCircleRegular,
  DismissRegular,
  DocumentRegular,
  DocumentTextRegular,
  DoorArrowRightRegular,
  EditRegular,
  EmojiRegular,
  ErrorCircleRegular,
  EyeOffRegular,
  EyeRegular,
  FilterRegular,
  FlashRegular,
  FolderAddRegular,
  FolderOpenRegular,
  FolderRegular,
  FullScreenMinimizeRegular,
  GlobeRegular,
  GridRegular,
  HeartRegular,
  HomeRegular,
  ImageRegular,
  InfoRegular,
  KeyboardRegular,
  LightbulbRegular,
  LinkRegular,
  ListRegular,
  LocalLanguageRegular,
  LocationRegular,
  LockClosedRegular,
  LockOpenRegular,
  MailInboxRegular,
  MailRegular,
  MapRegular,
  MaximizeRegular,
  MicRegular,
  MoreHorizontalRegular,
  MoreVerticalRegular,
  NavigationRegular,
  OpenRegular,
  PanelLeftRegular,
  PaymentRegular,
  PeopleRegular,
  PersonRegular,
  PersonSupportRegular,
  PhoneRegular,
  PinRegular,
  PulseRegular,
  QuestionCircleRegular,
  ReOrderDotsVerticalRegular,
  SaveRegular,
  SearchRegular,
  SendRegular,
  ServerRegular,
  SettingsRegular,
  ShareRegular,
  ShieldRegular,
  ShoppingBagRegular,
  SignOutRegular,
  SparkleRegular,
  Speaker2Regular,
  SpeakerOffRegular,
  StarRegular,
  SubtractRegular,
  TableRegular,
  TagRegular,
  TextBoldRegular,
  TextItalicRegular,
  TextUnderlineRegular,
  TimerRegular,
  WalletRegular,
  WandRegular,
  WarningRegular,
  WeatherMoonRegular,
  WeatherSunnyRegular,
  Wifi1Regular,
  WindowConsoleRegular,
  ZoomInRegular,
  ZoomOutRegular,
} from "@fluentui/react-icons";
import type React from "react";

const pack = {
  id: "fluent-outline",
  icons: {
    activity: PulseRegular,
    "alert-circle": ErrorCircleRegular,
    "alert-octagon": DismissCircleRegular,
    "alert-triangle": WarningRegular,
    archive: ArchiveRegular,
    "arrow-down": ArrowDownRegular,
    "arrow-left": ArrowLeftRegular,
    "arrow-right": ArrowRightRegular,
    "arrow-up": ArrowUpRegular,
    "arrow-up-right": ArrowUpRightRegular,
    "badge-check": CheckmarkStarburstRegular,
    bell: AlertRegular,
    bluetooth: BluetoothRegular,
    bold: TextBoldRegular,
    "book-open": BookRegular,
    bookmark: BookmarkRegular,
    bot: BotRegular,
    building: BuildingRegular,
    calculator: CalculatorRegular,
    calendar: CalendarRegular,
    camera: CameraRegular,
    "chart-bar": ChartMultipleRegular,
    "chart-line": DataLineRegular,
    "chart-pie": DataPieRegular,
    check: CheckmarkRegular,
    "check-circle": CheckmarkCircleRegular,
    "chevron-down": ChevronDownRegular,
    "chevron-left": ChevronLeftRegular,
    "chevron-right": ChevronRightRegular,
    "chevron-up": ChevronUpRegular,
    "chevrons-up-down": ChevronUpDownRegular,
    circle: CircleRegular,
    "circle-dashed": CircleHintRegular,
    clipboard: ClipboardRegular,
    "clipboard-paste": ClipboardPasteRegular,
    clock: ClockRegular,
    cloud: CloudRegular,
    code: CodeRegular,
    copy: CopyRegular,
    "credit-card": PaymentRegular,
    database: DatabaseRegular,
    delete: DeleteRegular,
    download: ArrowDownloadRegular,
    edit: EditRegular,
    "external-link": OpenRegular,
    eye: EyeRegular,
    "eye-off": EyeOffRegular,
    file: DocumentRegular,
    "file-code": CodeRegular,
    "file-text": DocumentTextRegular,
    filter: FilterRegular,
    folder: FolderRegular,
    "folder-open": FolderOpenRegular,
    "folder-plus": FolderAddRegular,
    "git-branch": BranchRegular,
    globe: GlobeRegular,
    "grip-vertical": ReOrderDotsVerticalRegular,
    heart: HeartRegular,
    "help-circle": QuestionCircleRegular,
    home: HomeRegular,
    image: ImageRegular,
    inbox: MailInboxRegular,
    info: InfoRegular,
    italic: TextItalicRegular,
    keyboard: KeyboardRegular,
    languages: LocalLanguageRegular,
    layout: BoardRegular,
    "layout-grid": GridRegular,
    "life-buoy": PersonSupportRegular,
    lightbulb: LightbulbRegular,
    link: LinkRegular,
    list: ListRegular,
    loader: ArrowClockwiseRegular,
    lock: LockClosedRegular,
    "log-in": DoorArrowRightRegular,
    "log-out": SignOutRegular,
    mail: MailRegular,
    map: MapRegular,
    "map-pin": LocationRegular,
    maximize: MaximizeRegular,
    menu: NavigationRegular,
    "message-square": ChatRegular,
    mic: MicRegular,
    minimize: FullScreenMinimizeRegular,
    minus: SubtractRegular,
    monitor: DesktopRegular,
    moon: WeatherMoonRegular,
    "more-horizontal": MoreHorizontalRegular,
    "more-vertical": MoreVerticalRegular,
    palette: ColorRegular,
    "panel-left": PanelLeftRegular,
    paperclip: AttachRegular,
    "pen-square": EditRegular,
    pin: PinRegular,
    plus: AddRegular,
    "plus-square": AddSquareRegular,
    refresh: ArrowClockwiseRegular,
    "rotate-cw": ArrowRotateClockwiseRegular,
    save: SaveRegular,
    scissors: CutRegular,
    search: SearchRegular,
    send: SendRegular,
    server: ServerRegular,
    settings: SettingsRegular,
    share: ShareRegular,
    shield: ShieldRegular,
    "shopping-bag": ShoppingBagRegular,
    "shopping-cart": CartRegular,
    smartphone: PhoneRegular,
    smile: EmojiRegular,
    sparkles: SparkleRegular,
    star: StarRegular,
    sun: WeatherSunnyRegular,
    table: TableRegular,
    tag: TagRegular,
    terminal: WindowConsoleRegular,
    timer: TimerRegular,
    trash: DeleteRegular,
    "trending-up": ArrowTrendingRegular,
    underline: TextUnderlineRegular,
    unlock: LockOpenRegular,
    upload: ArrowUploadRegular,
    user: PersonRegular,
    users: PeopleRegular,
    volume: Speaker2Regular,
    "volume-off": SpeakerOffRegular,
    wallet: WalletRegular,
    wand: WandRegular,
    wifi: Wifi1Regular,
    x: DismissRegular,
    "x-circle": DismissCircleRegular,
    zap: FlashRegular,
    "zoom-in": ZoomInRegular,
    "zoom-out": ZoomOutRegular,
  },
};

export default pack;
