"use client";

import {
  Activity,
  Archive,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  BadgeCheck,
  Bell,
  Bluetooth,
  Bold,
  Bookmark,
  BookOpen,
  Bot,
  Building2,
  Calculator,
  Calendar,
  Camera,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleDashed,
  CircleHelp,
  Clipboard,
  ClipboardPaste,
  Clock,
  Cloud,
  Code,
  Copy,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileCode,
  FileText,
  Folder,
  FolderOpen,
  FolderPlus,
  GitBranch,
  Globe,
  GripVertical,
  Heart,
  Home,
  Image,
  Inbox,
  Info,
  Italic,
  Keyboard,
  Languages,
  Layout,
  LayoutGrid,
  LifeBuoy,
  Lightbulb,
  Link,
  List,
  ListFilter,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map as MapIcon,
  MapPin,
  Maximize,
  Menu,
  MessageSquare,
  Mic,
  Minimize,
  Minus,
  Monitor,
  Moon,
  MoreHorizontal,
  MoreVertical,
  OctagonX,
  Palette,
  PanelLeft,
  Paperclip,
  Pencil,
  PenSquare,
  Pin,
  Plus,
  PlusSquare,
  RefreshCw,
  RotateCw,
  Save,
  Scissors,
  Search,
  Send,
  Server,
  Settings,
  Share,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Sun,
  Table,
  Tag,
  Terminal,
  Timer,
  Trash,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Underline,
  Unlock,
  Upload,
  User,
  Users,
  Volume2,
  VolumeX,
  Wallet,
  Wand,
  Wifi,
  X,
  XCircle,
  Zap,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
import type React from "react";

const pack = {
  id: "lucide",
  icons: {
    activity: Activity,
    "alert-circle": CircleAlert,
    "alert-octagon": OctagonX,
    "alert-triangle": TriangleAlert,
    archive: Archive,
    "arrow-down": ArrowDown,
    "arrow-left": ArrowLeft,
    "arrow-right": ArrowRight,
    "arrow-up": ArrowUp,
    "arrow-up-right": ArrowUpRight,
    "badge-check": BadgeCheck,
    bell: Bell,
    bluetooth: Bluetooth,
    bold: Bold,
    "book-open": BookOpen,
    bookmark: Bookmark,
    bot: Bot,
    building: Building2,
    calculator: Calculator,
    calendar: Calendar,
    camera: Camera,
    "chart-bar": ChartBar,
    "chart-line": ChartLine,
    "chart-pie": ChartPie,
    check: Check,
    "check-circle": CheckCircle2,
    "chevron-down": ChevronDown,
    "chevron-left": ChevronLeft,
    "chevron-right": ChevronRight,
    "chevron-up": ChevronUp,
    "chevrons-up-down": ChevronsUpDown,
    circle: Circle,
    "circle-dashed": CircleDashed,
    clipboard: Clipboard,
    "clipboard-paste": ClipboardPaste,
    clock: Clock,
    cloud: Cloud,
    code: Code,
    copy: Copy,
    "credit-card": CreditCard,
    database: Database,
    delete: Trash2,
    download: Download,
    edit: Pencil,
    "external-link": ExternalLink,
    eye: Eye,
    "eye-off": EyeOff,
    file: File,
    "file-code": FileCode,
    "file-text": FileText,
    filter: ListFilter,
    folder: Folder,
    "folder-open": FolderOpen,
    "folder-plus": FolderPlus,
    "git-branch": GitBranch,
    globe: Globe,
    "grip-vertical": GripVertical,
    heart: Heart,
    "help-circle": CircleHelp,
    home: Home,
    image: Image,
    inbox: Inbox,
    info: Info,
    italic: Italic,
    keyboard: Keyboard,
    languages: Languages,
    layout: Layout,
    "layout-grid": LayoutGrid,
    "life-buoy": LifeBuoy,
    lightbulb: Lightbulb,
    link: Link,
    list: List,
    loader: Loader2,
    lock: Lock,
    "log-in": LogIn,
    "log-out": LogOut,
    mail: Mail,
    map: MapIcon,
    "map-pin": MapPin,
    maximize: Maximize,
    menu: Menu,
    "message-square": MessageSquare,
    mic: Mic,
    minimize: Minimize,
    minus: Minus,
    monitor: Monitor,
    moon: Moon,
    "more-horizontal": MoreHorizontal,
    "more-vertical": MoreVertical,
    palette: Palette,
    "panel-left": PanelLeft,
    paperclip: Paperclip,
    "pen-square": PenSquare,
    pin: Pin,
    plus: Plus,
    "plus-square": PlusSquare,
    refresh: RefreshCw,
    "rotate-cw": RotateCw,
    save: Save,
    scissors: Scissors,
    search: Search,
    send: Send,
    server: Server,
    settings: Settings,
    share: Share,
    shield: Shield,
    "shopping-bag": ShoppingBag,
    "shopping-cart": ShoppingCart,
    smartphone: Smartphone,
    smile: Smile,
    sparkles: Sparkles,
    star: Star,
    sun: Sun,
    table: Table,
    tag: Tag,
    terminal: Terminal,
    timer: Timer,
    trash: Trash,
    "trending-up": TrendingUp,
    underline: Underline,
    unlock: Unlock,
    upload: Upload,
    user: User,
    users: Users,
    volume: Volume2,
    "volume-off": VolumeX,
    wallet: Wallet,
    wand: Wand,
    wifi: Wifi,
    x: X,
    "x-circle": XCircle,
    zap: Zap,
    "zoom-in": ZoomIn,
    "zoom-out": ZoomOut,
  },
};

export default pack;
