"use client";

import {
  IconActivity,
  IconAlarm,
  IconAlertCircle,
  IconAlertOctagon,
  IconAlertTriangle,
  IconArchive,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowUpRight,
  IconBell,
  IconBluetooth,
  IconBold,
  IconBolt,
  IconBook,
  IconBookmark,
  IconBuildingBank,
  IconBulb,
  IconCalculator,
  IconCalendar,
  IconCamera,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconCircle,
  IconCircleCheck,
  IconCircleDashed,
  IconCircleX,
  IconClipboard,
  IconClock,
  IconCloud,
  IconCode,
  IconCopy,
  IconCreditCard,
  IconCut,
  IconDatabase,
  IconDeviceDesktop,
  IconDeviceFloppy,
  IconDeviceMobile,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeClosed,
  IconFile,
  IconFileCode,
  IconFileText,
  IconFilterPlus,
  IconFolder,
  IconFolderOpen,
  IconFolderPlus,
  IconGitBranch,
  IconGripVertical,
  IconHeart,
  IconHelpCircle,
  IconHome,
  IconInbox,
  IconInfoCircle,
  IconItalic,
  IconKeyboard,
  IconLanguage,
  IconLayout,
  IconLayoutGrid,
  IconLayoutSidebar,
  IconLifebuoy,
  IconLink,
  IconList,
  IconLoader2,
  IconLock,
  IconLockOpen,
  IconLogin,
  IconLogout,
  IconMail,
  IconMap,
  IconMapPin,
  IconMaximize,
  IconMenu,
  IconMessage,
  IconMicrophone,
  IconMinimize,
  IconMinus,
  IconMoodSmile,
  IconMoon,
  IconPalette,
  IconPaperclip,
  IconPencil,
  IconPhoto,
  IconPinned,
  IconPlus,
  IconRefresh,
  IconRobot,
  IconRosetteDiscountCheck,
  IconRotateClockwise2,
  IconSearch,
  IconSelector,
  IconSend,
  IconServer,
  IconSettings,
  IconShare,
  IconShield,
  IconShoppingBag,
  IconShoppingCart,
  IconSparkles,
  IconSquarePlus,
  IconStar,
  IconSun,
  IconTable,
  IconTag,
  IconTerminal,
  IconTrash,
  IconTrendingUp,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUsers,
  IconVolume,
  IconVolumeOff,
  IconWallet,
  IconWand,
  IconWifi,
  IconWorld,
  IconX,
  IconZoomIn,
  IconZoomOut,
} from "@tabler/icons-react";
import type React from "react";

const pack = {
  id: "tabler-outline",
  icons: {
    activity: IconActivity,
    "alert-circle": IconAlertCircle,
    "alert-octagon": IconAlertOctagon,
    "alert-triangle": IconAlertTriangle,
    archive: IconArchive,
    "arrow-down": IconArrowDown,
    "arrow-left": IconArrowLeft,
    "arrow-right": IconArrowRight,
    "arrow-up": IconArrowUp,
    "arrow-up-right": IconArrowUpRight,
    "badge-check": IconRosetteDiscountCheck,
    bell: IconBell,
    bluetooth: IconBluetooth,
    bold: IconBold,
    "book-open": IconBook,
    bookmark: IconBookmark,
    bot: IconRobot,
    building: IconBuildingBank,
    calculator: IconCalculator,
    calendar: IconCalendar,
    camera: IconCamera,
    "chart-bar": IconChartBar,
    "chart-line": IconChartLine,
    "chart-pie": IconChartPie,
    check: IconCheck,
    "check-circle": IconCircleCheck,
    "chevron-down": IconChevronDown,
    "chevron-left": IconChevronLeft,
    "chevron-right": IconChevronRight,
    "chevron-up": IconChevronUp,
    "chevrons-up-down": IconSelector,
    circle: IconCircle,
    "circle-dashed": IconCircleDashed,
    clipboard: IconClipboard,
    "clipboard-paste": IconClipboard,
    clock: IconClock,
    cloud: IconCloud,
    code: IconCode,
    copy: IconCopy,
    "credit-card": IconCreditCard,
    database: IconDatabase,
    delete: IconTrash,
    download: IconDownload,
    edit: IconPencil,
    "external-link": IconExternalLink,
    eye: IconEye,
    "eye-off": IconEyeClosed,
    file: IconFile,
    "file-code": IconFileCode,
    "file-text": IconFileText,
    filter: IconFilterPlus,
    folder: IconFolder,
    "folder-open": IconFolderOpen,
    "folder-plus": IconFolderPlus,
    "git-branch": IconGitBranch,
    globe: IconWorld,
    "grip-vertical": IconGripVertical,
    heart: IconHeart,
    "help-circle": IconHelpCircle,
    home: IconHome,
    image: IconPhoto,
    inbox: IconInbox,
    info: IconInfoCircle,
    italic: IconItalic,
    keyboard: IconKeyboard,
    languages: IconLanguage,
    layout: IconLayout,
    "layout-grid": IconLayoutGrid,
    "life-buoy": IconLifebuoy,
    lightbulb: IconBulb,
    link: IconLink,
    list: IconList,
    loader: IconLoader2,
    lock: IconLock,
    "log-in": IconLogin,
    "log-out": IconLogout,
    mail: IconMail,
    map: IconMap,
    "map-pin": IconMapPin,
    maximize: IconMaximize,
    menu: IconMenu,
    "message-square": IconMessage,
    mic: IconMicrophone,
    minimize: IconMinimize,
    minus: IconMinus,
    monitor: IconDeviceDesktop,
    moon: IconMoon,
    "more-horizontal": IconDots,
    "more-vertical": IconDotsVertical,
    palette: IconPalette,
    "panel-left": IconLayoutSidebar,
    paperclip: IconPaperclip,
    "pen-square": IconEdit,
    pin: IconPinned,
    plus: IconPlus,
    "plus-square": IconSquarePlus,
    refresh: IconRefresh,
    "rotate-cw": IconRotateClockwise2,
    save: IconDeviceFloppy,
    scissors: IconCut,
    search: IconSearch,
    send: IconSend,
    server: IconServer,
    settings: IconSettings,
    share: IconShare,
    shield: IconShield,
    "shopping-bag": IconShoppingBag,
    "shopping-cart": IconShoppingCart,
    smartphone: IconDeviceMobile,
    smile: IconMoodSmile,
    sparkles: IconSparkles,
    star: IconStar,
    sun: IconSun,
    table: IconTable,
    tag: IconTag,
    terminal: IconTerminal,
    timer: IconAlarm,
    trash: IconTrash,
    "trending-up": IconTrendingUp,
    underline: IconUnderline,
    unlock: IconLockOpen,
    upload: IconUpload,
    user: IconUser,
    users: IconUsers,
    volume: IconVolume,
    "volume-off": IconVolumeOff,
    wallet: IconWallet,
    wand: IconWand,
    wifi: IconWifi,
    x: IconX,
    "x-circle": IconCircleX,
    zap: IconBolt,
    "zoom-in": IconZoomIn,
    "zoom-out": IconZoomOut,
  },
};

export default pack;
