"use client";

import {
  AddFilled,
  AddSquareFilled,
  AlertFilled,
  ArchiveFilled,
  ArrowClockwiseFilled,
  ArrowDownFilled,
  ArrowDownloadFilled,
  ArrowLeftFilled,
  ArrowRightFilled,
  ArrowRotateClockwiseFilled,
  ArrowTrendingFilled,
  ArrowUpFilled,
  ArrowUploadFilled,
  ArrowUpRightFilled,
  AttachFilled,
  BluetoothFilled,
  BoardFilled,
  BookFilled,
  BookmarkFilled,
  BotFilled,
  BranchFilled,
  BuildingFilled,
  CalculatorFilled,
  CalendarFilled,
  CameraFilled,
  CartFilled,
  ChartMultipleFilled,
  ChatFilled,
  CheckmarkCircleFilled,
  CheckmarkFilled,
  CheckmarkStarburstFilled,
  ChevronDownFilled,
  ChevronLeftFilled,
  ChevronRightFilled,
  ChevronUpDownFilled,
  ChevronUpFilled,
  CircleFilled,
  CircleHintFilled,
  ClipboardFilled,
  ClipboardPasteFilled,
  ClockFilled,
  CloudFilled,
  CodeFilled,
  ColorFilled,
  CopyFilled,
  CutFilled,
  DatabaseFilled,
  DataLineFilled,
  DataPieFilled,
  DeleteFilled,
  DesktopFilled,
  DismissCircleFilled,
  DismissFilled,
  DocumentFilled,
  DocumentTextFilled,
  DoorArrowRightFilled,
  EditFilled,
  EmojiFilled,
  ErrorCircleFilled,
  EyeFilled,
  EyeOffFilled,
  FilterFilled,
  FlashFilled,
  FolderAddFilled,
  FolderFilled,
  FolderOpenFilled,
  FullScreenMinimizeFilled,
  GlobeFilled,
  GridFilled,
  HeartFilled,
  HomeFilled,
  ImageFilled,
  InfoFilled,
  KeyboardFilled,
  LightbulbFilled,
  LinkFilled,
  ListFilled,
  LocalLanguageFilled,
  LocationFilled,
  LockClosedFilled,
  LockOpenFilled,
  MailFilled,
  MailInboxFilled,
  MapFilled,
  MaximizeFilled,
  MicFilled,
  MoreHorizontalFilled,
  MoreVerticalFilled,
  NavigationFilled,
  OpenFilled,
  PanelLeftFilled,
  PaymentFilled,
  PeopleFilled,
  PersonFilled,
  PersonSupportFilled,
  PhoneFilled,
  PinFilled,
  PulseFilled,
  QuestionCircleFilled,
  ReOrderDotsVerticalFilled,
  SaveFilled,
  SearchFilled,
  SendFilled,
  ServerFilled,
  SettingsFilled,
  ShareFilled,
  ShieldFilled,
  ShoppingBagFilled,
  SignOutFilled,
  SparkleFilled,
  Speaker2Filled,
  SpeakerOffFilled,
  StarFilled,
  SubtractFilled,
  TableFilled,
  TagFilled,
  TextBoldFilled,
  TextItalicFilled,
  TextUnderlineFilled,
  TimerFilled,
  WalletFilled,
  WandFilled,
  WarningFilled,
  WeatherMoonFilled,
  WeatherSunnyFilled,
  Wifi1Filled,
  WindowConsoleFilled,
  ZoomInFilled,
  ZoomOutFilled,
} from "@fluentui/react-icons";
import type React from "react";

const pack = {
  id: "fluent-filled",
  icons: {
    activity: PulseFilled,
    "alert-circle": ErrorCircleFilled,
    "alert-octagon": DismissCircleFilled,
    "alert-triangle": WarningFilled,
    archive: ArchiveFilled,
    "arrow-down": ArrowDownFilled,
    "arrow-left": ArrowLeftFilled,
    "arrow-right": ArrowRightFilled,
    "arrow-up": ArrowUpFilled,
    "arrow-up-right": ArrowUpRightFilled,
    "badge-check": CheckmarkStarburstFilled,
    bell: AlertFilled,
    bluetooth: BluetoothFilled,
    bold: TextBoldFilled,
    "book-open": BookFilled,
    bookmark: BookmarkFilled,
    bot: BotFilled,
    building: BuildingFilled,
    calculator: CalculatorFilled,
    calendar: CalendarFilled,
    camera: CameraFilled,
    "chart-bar": ChartMultipleFilled,
    "chart-line": DataLineFilled,
    "chart-pie": DataPieFilled,
    check: CheckmarkFilled,
    "check-circle": CheckmarkCircleFilled,
    "chevron-down": ChevronDownFilled,
    "chevron-left": ChevronLeftFilled,
    "chevron-right": ChevronRightFilled,
    "chevron-up": ChevronUpFilled,
    "chevrons-up-down": ChevronUpDownFilled,
    circle: CircleFilled,
    "circle-dashed": CircleHintFilled,
    clipboard: ClipboardFilled,
    "clipboard-paste": ClipboardPasteFilled,
    clock: ClockFilled,
    cloud: CloudFilled,
    code: CodeFilled,
    copy: CopyFilled,
    "credit-card": PaymentFilled,
    database: DatabaseFilled,
    delete: DeleteFilled,
    download: ArrowDownloadFilled,
    edit: EditFilled,
    "external-link": OpenFilled,
    eye: EyeFilled,
    "eye-off": EyeOffFilled,
    file: DocumentFilled,
    "file-code": CodeFilled,
    "file-text": DocumentTextFilled,
    filter: FilterFilled,
    folder: FolderFilled,
    "folder-open": FolderOpenFilled,
    "folder-plus": FolderAddFilled,
    "git-branch": BranchFilled,
    globe: GlobeFilled,
    "grip-vertical": ReOrderDotsVerticalFilled,
    heart: HeartFilled,
    "help-circle": QuestionCircleFilled,
    home: HomeFilled,
    image: ImageFilled,
    inbox: MailInboxFilled,
    info: InfoFilled,
    italic: TextItalicFilled,
    keyboard: KeyboardFilled,
    languages: LocalLanguageFilled,
    layout: BoardFilled,
    "layout-grid": GridFilled,
    "life-buoy": PersonSupportFilled,
    lightbulb: LightbulbFilled,
    link: LinkFilled,
    list: ListFilled,
    loader: ArrowClockwiseFilled,
    lock: LockClosedFilled,
    "log-in": DoorArrowRightFilled,
    "log-out": SignOutFilled,
    mail: MailFilled,
    map: MapFilled,
    "map-pin": LocationFilled,
    maximize: MaximizeFilled,
    menu: NavigationFilled,
    "message-square": ChatFilled,
    mic: MicFilled,
    minimize: FullScreenMinimizeFilled,
    minus: SubtractFilled,
    monitor: DesktopFilled,
    moon: WeatherMoonFilled,
    "more-horizontal": MoreHorizontalFilled,
    "more-vertical": MoreVerticalFilled,
    palette: ColorFilled,
    "panel-left": PanelLeftFilled,
    paperclip: AttachFilled,
    "pen-square": EditFilled,
    pin: PinFilled,
    plus: AddFilled,
    "plus-square": AddSquareFilled,
    refresh: ArrowClockwiseFilled,
    "rotate-cw": ArrowRotateClockwiseFilled,
    save: SaveFilled,
    scissors: CutFilled,
    search: SearchFilled,
    send: SendFilled,
    server: ServerFilled,
    settings: SettingsFilled,
    share: ShareFilled,
    shield: ShieldFilled,
    "shopping-bag": ShoppingBagFilled,
    "shopping-cart": CartFilled,
    smartphone: PhoneFilled,
    smile: EmojiFilled,
    sparkles: SparkleFilled,
    star: StarFilled,
    sun: WeatherSunnyFilled,
    table: TableFilled,
    tag: TagFilled,
    terminal: WindowConsoleFilled,
    timer: TimerFilled,
    trash: DeleteFilled,
    "trending-up": ArrowTrendingFilled,
    underline: TextUnderlineFilled,
    unlock: LockOpenFilled,
    upload: ArrowUploadFilled,
    user: PersonFilled,
    users: PeopleFilled,
    volume: Speaker2Filled,
    "volume-off": SpeakerOffFilled,
    wallet: WalletFilled,
    wand: WandFilled,
    wifi: Wifi1Filled,
    x: DismissFilled,
    "x-circle": DismissCircleFilled,
    zap: FlashFilled,
    "zoom-in": ZoomInFilled,
    "zoom-out": ZoomOutFilled,
  },
};

export default pack;
