/**
 * Curated common UI icons: semantic name, Lucide export key, Tabler outline export.
 * Lucide keys match lucide-react exports (Icon suffix optional).
 */
export const commonIconSeeds = [
  { semantic: "search", lucide: "Search", tabler: "IconSearch" },
  { semantic: "x", lucide: "X", tabler: "IconX" },
  { semantic: "x-circle", lucide: "XCircle", tabler: "IconCircleX" },
  { semantic: "check", lucide: "Check", tabler: "IconCheck" },
  {
    semantic: "check-circle",
    lucide: "CheckCircle2",
    tabler: "IconCircleCheck",
  },
  { semantic: "plus", lucide: "Plus", tabler: "IconPlus" },
  { semantic: "plus-square", lucide: "PlusSquare", tabler: "IconSquarePlus" },
  { semantic: "minus", lucide: "Minus", tabler: "IconMinus" },
  {
    semantic: "chevron-left",
    lucide: "ChevronLeft",
    tabler: "IconChevronLeft",
  },
  {
    semantic: "chevron-right",
    lucide: "ChevronRight",
    tabler: "IconChevronRight",
  },
  {
    semantic: "chevron-down",
    lucide: "ChevronDown",
    tabler: "IconChevronDown",
  },
  { semantic: "chevron-up", lucide: "ChevronUp", tabler: "IconChevronUp" },
  {
    semantic: "chevrons-up-down",
    lucide: "ChevronsUpDown",
    tabler: "IconSelector",
  },
  { semantic: "arrow-left", lucide: "ArrowLeft", tabler: "IconArrowLeft" },
  { semantic: "arrow-right", lucide: "ArrowRight", tabler: "IconArrowRight" },
  { semantic: "arrow-up", lucide: "ArrowUp", tabler: "IconArrowUp" },
  { semantic: "arrow-down", lucide: "ArrowDown", tabler: "IconArrowDown" },
  {
    semantic: "arrow-up-right",
    lucide: "ArrowUpRight",
    tabler: "IconArrowUpRight",
  },
  { semantic: "more-horizontal", lucide: "MoreHorizontal", tabler: "IconDots" },
  {
    semantic: "more-vertical",
    lucide: "MoreVertical",
    tabler: "IconDotsVertical",
  },
  { semantic: "home", lucide: "Home", tabler: "IconHome" },
  { semantic: "settings", lucide: "Settings", tabler: "IconSettings" },
  { semantic: "menu", lucide: "Menu", tabler: "IconMenu" },
  { semantic: "user", lucide: "User", tabler: "IconUser" },
  { semantic: "users", lucide: "Users", tabler: "IconUsers" },
  { semantic: "mail", lucide: "Mail", tabler: "IconMail" },
  { semantic: "bell", lucide: "Bell", tabler: "IconBell" },
  { semantic: "calendar", lucide: "Calendar", tabler: "IconCalendar" },
  { semantic: "clock", lucide: "Clock", tabler: "IconClock" },
  { semantic: "timer", lucide: "Timer", tabler: "IconAlarm" },
  { semantic: "download", lucide: "Download", tabler: "IconDownload" },
  { semantic: "upload", lucide: "Upload", tabler: "IconUpload" },
  { semantic: "delete", lucide: "Trash2", tabler: "IconTrash" },
  { semantic: "trash", lucide: "Trash", tabler: "IconTrash" },
  { semantic: "edit", lucide: "Pencil", tabler: "IconPencil" },
  { semantic: "pen-square", lucide: "PenSquare", tabler: "IconEdit" },
  { semantic: "copy", lucide: "Copy", tabler: "IconCopy" },
  { semantic: "save", lucide: "Save", tabler: "IconDeviceFloppy" },
  { semantic: "share", lucide: "Share", tabler: "IconShare" },
  { semantic: "link", lucide: "Link", tabler: "IconLink" },
  {
    semantic: "external-link",
    lucide: "ExternalLink",
    tabler: "IconExternalLink",
  },
  { semantic: "folder", lucide: "Folder", tabler: "IconFolder" },
  { semantic: "folder-open", lucide: "FolderOpen", tabler: "IconFolderOpen" },
  { semantic: "folder-plus", lucide: "FolderPlus", tabler: "IconFolderPlus" },
  { semantic: "file", lucide: "File", tabler: "IconFile" },
  { semantic: "file-text", lucide: "FileText", tabler: "IconFileText" },
  { semantic: "file-code", lucide: "FileCode", tabler: "IconFileCode" },
  { semantic: "image", lucide: "Image", tabler: "IconPhoto" },
  { semantic: "eye", lucide: "Eye", tabler: "IconEye" },
  { semantic: "eye-off", lucide: "EyeOff", tabler: "IconEyeClosed" },
  { semantic: "lock", lucide: "Lock", tabler: "IconLock" },
  { semantic: "unlock", lucide: "Unlock", tabler: "IconLockOpen" },
  { semantic: "star", lucide: "Star", tabler: "IconStar" },
  { semantic: "heart", lucide: "Heart", tabler: "IconHeart" },
  { semantic: "bookmark", lucide: "Bookmark", tabler: "IconBookmark" },
  { semantic: "tag", lucide: "Tag", tabler: "IconTag" },
  { semantic: "filter", lucide: "ListFilter", tabler: "IconFilterPlus" },
  { semantic: "list", lucide: "List", tabler: "IconList" },
  { semantic: "layout-grid", lucide: "LayoutGrid", tabler: "IconLayoutGrid" },
  { semantic: "layout", lucide: "Layout", tabler: "IconLayout" },
  { semantic: "panel-left", lucide: "PanelLeft", tabler: "IconLayoutSidebar" },
  { semantic: "table", lucide: "Table", tabler: "IconTable" },
  { semantic: "loader", lucide: "Loader2", tabler: "IconLoader2" },
  { semantic: "refresh", lucide: "RefreshCw", tabler: "IconRefresh" },
  { semantic: "rotate-cw", lucide: "RotateCw", tabler: "IconRotateClockwise2" },
  { semantic: "info", lucide: "Info", tabler: "IconInfoCircle" },
  {
    semantic: "alert-circle",
    lucide: "CircleAlert",
    tabler: "IconAlertCircle",
  },
  {
    semantic: "alert-triangle",
    lucide: "TriangleAlert",
    tabler: "IconAlertTriangle",
  },
  { semantic: "alert-octagon", lucide: "OctagonX", tabler: "IconAlertOctagon" },
  { semantic: "help-circle", lucide: "CircleHelp", tabler: "IconHelpCircle" },
  { semantic: "sun", lucide: "Sun", tabler: "IconSun" },
  { semantic: "moon", lucide: "Moon", tabler: "IconMoon" },
  { semantic: "palette", lucide: "Palette", tabler: "IconPalette" },
  { semantic: "monitor", lucide: "Monitor", tabler: "IconDeviceDesktop" },
  { semantic: "smartphone", lucide: "Smartphone", tabler: "IconDeviceMobile" },
  { semantic: "terminal", lucide: "Terminal", tabler: "IconTerminal" },
  { semantic: "code", lucide: "Code", tabler: "IconCode" },
  { semantic: "git-branch", lucide: "GitBranch", tabler: "IconGitBranch" },
  { semantic: "server", lucide: "Server", tabler: "IconServer" },
  { semantic: "cloud", lucide: "Cloud", tabler: "IconCloud" },
  { semantic: "database", lucide: "Database", tabler: "IconDatabase" },
  { semantic: "wifi", lucide: "Wifi", tabler: "IconWifi" },
  { semantic: "bluetooth", lucide: "Bluetooth", tabler: "IconBluetooth" },
  { semantic: "camera", lucide: "Camera", tabler: "IconCamera" },
  { semantic: "mic", lucide: "Mic", tabler: "IconMicrophone" },
  { semantic: "volume", lucide: "Volume2", tabler: "IconVolume" },
  { semantic: "volume-off", lucide: "VolumeX", tabler: "IconVolumeOff" },
  { semantic: "paperclip", lucide: "Paperclip", tabler: "IconPaperclip" },
  { semantic: "send", lucide: "Send", tabler: "IconSend" },
  {
    semantic: "message-square",
    lucide: "MessageSquare",
    tabler: "IconMessage",
  },
  { semantic: "inbox", lucide: "Inbox", tabler: "IconInbox" },
  { semantic: "archive", lucide: "Archive", tabler: "IconArchive" },
  { semantic: "log-in", lucide: "LogIn", tabler: "IconLogin" },
  { semantic: "log-out", lucide: "LogOut", tabler: "IconLogout" },
  {
    semantic: "shopping-cart",
    lucide: "ShoppingCart",
    tabler: "IconShoppingCart",
  },
  {
    semantic: "shopping-bag",
    lucide: "ShoppingBag",
    tabler: "IconShoppingBag",
  },
  { semantic: "credit-card", lucide: "CreditCard", tabler: "IconCreditCard" },
  { semantic: "wallet", lucide: "Wallet", tabler: "IconWallet" },
  { semantic: "map", lucide: "Map", tabler: "IconMap" },
  { semantic: "globe", lucide: "Globe", tabler: "IconWorld" },
  { semantic: "map-pin", lucide: "MapPin", tabler: "IconMapPin" },
  { semantic: "building", lucide: "Building2", tabler: "IconBuildingBank" },
  { semantic: "zap", lucide: "Zap", tabler: "IconBolt" },
  { semantic: "lightbulb", lucide: "Lightbulb", tabler: "IconBulb" },
  { semantic: "sparkles", lucide: "Sparkles", tabler: "IconSparkles" },
  { semantic: "bot", lucide: "Bot", tabler: "IconRobot" },
  { semantic: "wand", lucide: "Wand", tabler: "IconWand" },
  { semantic: "pin", lucide: "Pin", tabler: "IconPinned" },
  {
    semantic: "grip-vertical",
    lucide: "GripVertical",
    tabler: "IconGripVertical",
  },
  { semantic: "maximize", lucide: "Maximize", tabler: "IconMaximize" },
  { semantic: "minimize", lucide: "Minimize", tabler: "IconMinimize" },
  { semantic: "zoom-in", lucide: "ZoomIn", tabler: "IconZoomIn" },
  { semantic: "zoom-out", lucide: "ZoomOut", tabler: "IconZoomOut" },
  { semantic: "bold", lucide: "Bold", tabler: "IconBold" },
  { semantic: "italic", lucide: "Italic", tabler: "IconItalic" },
  { semantic: "underline", lucide: "Underline", tabler: "IconUnderline" },
  { semantic: "scissors", lucide: "Scissors", tabler: "IconCut" },
  { semantic: "clipboard", lucide: "Clipboard", tabler: "IconClipboard" },
  {
    semantic: "clipboard-paste",
    lucide: "ClipboardPaste",
    tabler: "IconClipboard",
  },
  { semantic: "chart-line", lucide: "ChartLine", tabler: "IconChartLine" },
  { semantic: "chart-bar", lucide: "ChartBar", tabler: "IconChartBar" },
  { semantic: "chart-pie", lucide: "ChartPie", tabler: "IconChartPie" },
  { semantic: "trending-up", lucide: "TrendingUp", tabler: "IconTrendingUp" },
  { semantic: "activity", lucide: "Activity", tabler: "IconActivity" },
  { semantic: "calculator", lucide: "Calculator", tabler: "IconCalculator" },
  { semantic: "shield", lucide: "Shield", tabler: "IconShield" },
  { semantic: "keyboard", lucide: "Keyboard", tabler: "IconKeyboard" },
  { semantic: "languages", lucide: "Languages", tabler: "IconLanguage" },
  { semantic: "book-open", lucide: "BookOpen", tabler: "IconBook" },
  { semantic: "life-buoy", lucide: "LifeBuoy", tabler: "IconLifebuoy" },
  { semantic: "circle", lucide: "Circle", tabler: "IconCircle" },
  {
    semantic: "circle-dashed",
    lucide: "CircleDashed",
    tabler: "IconCircleDashed",
  },
  { semantic: "smile", lucide: "Smile", tabler: "IconMoodSmile" },
  {
    semantic: "badge-check",
    lucide: "BadgeCheck",
    tabler: "IconRosetteDiscountCheck",
  },
] as const;
