"use client";

import {
  ArchiveBoxIcon,
  ArrowDownIcon,
  ArrowDownTrayIcon,
  ArrowLeftIcon,
  ArrowLeftOnRectangleIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowRightOnRectangleIcon,
  ArrowsPointingInIcon,
  ArrowsPointingOutIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingUpIcon,
  ArrowUpIcon,
  ArrowUpRightIcon,
  ArrowUpTrayIcon,
  Bars3BottomLeftIcon,
  Bars3Icon,
  BellIcon,
  BoldIcon,
  BoltIcon,
  BookmarkIcon,
  BookOpenIcon,
  BuildingOffice2Icon,
  CalculatorIcon,
  CalendarIcon,
  CameraIcon,
  ChartBarIcon,
  ChartBarSquareIcon,
  ChartPieIcon,
  ChatBubbleLeftIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClipboardDocumentIcon,
  ClipboardIcon,
  ClockIcon,
  CloudIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  Cog6ToothIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  CpuChipIcon,
  CreditCardIcon,
  DevicePhoneMobileIcon,
  DocumentArrowDownIcon,
  DocumentDuplicateIcon,
  DocumentIcon,
  DocumentTextIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  EnvelopeIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FaceSmileIcon,
  FolderIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  FunnelIcon,
  GlobeAltIcon,
  HeartIcon,
  HomeIcon,
  InboxIcon,
  InformationCircleIcon,
  ItalicIcon,
  LanguageIcon,
  LightBulbIcon,
  LinkIcon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassPlusIcon,
  MapIcon,
  MapPinIcon,
  MicrophoneIcon,
  MinusIcon,
  MoonIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PencilIcon,
  PencilSquareIcon,
  PhotoIcon,
  PlusCircleIcon,
  PlusIcon,
  QuestionMarkCircleIcon,
  RectangleGroupIcon,
  ScissorsIcon,
  ServerIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SignalIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  Squares2X2Icon,
  StarIcon,
  SunIcon,
  SwatchIcon,
  TableCellsIcon,
  TagIcon,
  TrashIcon,
  UnderlineIcon,
  UserCircleIcon,
  UserIcon,
  UsersIcon,
  WalletIcon,
  WifiIcon,
  XCircleIcon,
  XMarkIcon,
} from "@heroicons/react/24/solid";
import type React from "react";

const pack = {
  id: "heroicons-solid",
  icons: {
    activity: BoltIcon,
    "alert-circle": ExclamationCircleIcon,
    "alert-octagon": XCircleIcon,
    "alert-triangle": ExclamationTriangleIcon,
    archive: ArchiveBoxIcon,
    "arrow-down": ArrowDownIcon,
    "arrow-left": ArrowLeftIcon,
    "arrow-right": ArrowRightIcon,
    "arrow-up": ArrowUpIcon,
    "arrow-up-right": ArrowUpRightIcon,
    "badge-check": CheckBadgeIcon,
    bell: BellIcon,
    bluetooth: SignalIcon,
    bold: BoldIcon,
    "book-open": BookOpenIcon,
    bookmark: BookmarkIcon,
    bot: CpuChipIcon,
    building: BuildingOffice2Icon,
    calculator: CalculatorIcon,
    calendar: CalendarIcon,
    camera: CameraIcon,
    "chart-bar": ChartBarSquareIcon,
    "chart-line": ChartBarIcon,
    "chart-pie": ChartPieIcon,
    check: CheckIcon,
    "check-circle": CheckCircleIcon,
    "chevron-down": ChevronDownIcon,
    "chevron-left": ChevronLeftIcon,
    "chevron-right": ChevronRightIcon,
    "chevron-up": ChevronUpIcon,
    "chevrons-up-down": ChevronUpDownIcon,
    circle: CircleStackIcon,
    "circle-dashed": CircleStackIcon,
    "circle-user": UserCircleIcon,
    clipboard: ClipboardIcon,
    "clipboard-paste": ClipboardDocumentIcon,
    clock: ClockIcon,
    cloud: CloudIcon,
    code: CodeBracketIcon,
    copy: DocumentDuplicateIcon,
    "credit-card": CreditCardIcon,
    database: CircleStackIcon,
    delete: TrashIcon,
    download: ArrowDownTrayIcon,
    edit: PencilIcon,
    "external-link": ArrowTopRightOnSquareIcon,
    eye: EyeIcon,
    "eye-off": EyeSlashIcon,
    file: DocumentIcon,
    "file-code": DocumentTextIcon,
    "file-text": DocumentTextIcon,
    filter: FunnelIcon,
    folder: FolderIcon,
    "folder-open": FolderOpenIcon,
    "folder-plus": FolderPlusIcon,
    "git-branch": CodeBracketSquareIcon,
    globe: GlobeAltIcon,
    "grip-vertical": Bars3Icon,
    heart: HeartIcon,
    "help-circle": QuestionMarkCircleIcon,
    home: HomeIcon,
    image: PhotoIcon,
    inbox: InboxIcon,
    info: InformationCircleIcon,
    italic: ItalicIcon,
    keyboard: CommandLineIcon,
    languages: LanguageIcon,
    layout: RectangleGroupIcon,
    "layout-grid": Squares2X2Icon,
    "life-buoy": QuestionMarkCircleIcon,
    lightbulb: LightBulbIcon,
    link: LinkIcon,
    list: ListBulletIcon,
    loader: ArrowPathIcon,
    lock: LockClosedIcon,
    "log-in": ArrowLeftOnRectangleIcon,
    "log-out": ArrowRightOnRectangleIcon,
    mail: EnvelopeIcon,
    map: MapIcon,
    "map-pin": MapPinIcon,
    maximize: ArrowsPointingOutIcon,
    menu: Bars3Icon,
    "message-square": ChatBubbleLeftIcon,
    mic: MicrophoneIcon,
    minimize: ArrowsPointingInIcon,
    minus: MinusIcon,
    monitor: ComputerDesktopIcon,
    moon: MoonIcon,
    "more-horizontal": EllipsisHorizontalIcon,
    "more-vertical": EllipsisVerticalIcon,
    palette: SwatchIcon,
    "panel-left": Bars3BottomLeftIcon,
    paperclip: PaperClipIcon,
    "pen-square": PencilSquareIcon,
    pin: BookmarkIcon,
    plus: PlusIcon,
    "plus-square": PlusCircleIcon,
    refresh: ArrowPathIcon,
    "rotate-cw": ArrowPathIcon,
    save: DocumentArrowDownIcon,
    scissors: ScissorsIcon,
    search: MagnifyingGlassIcon,
    send: PaperAirplaneIcon,
    server: ServerIcon,
    settings: Cog6ToothIcon,
    share: ShareIcon,
    shield: ShieldCheckIcon,
    "shopping-bag": ShoppingBagIcon,
    "shopping-cart": ShoppingCartIcon,
    smartphone: DevicePhoneMobileIcon,
    smile: FaceSmileIcon,
    sparkles: SparklesIcon,
    star: StarIcon,
    sun: SunIcon,
    table: TableCellsIcon,
    tag: TagIcon,
    terminal: CommandLineIcon,
    timer: ClockIcon,
    trash: TrashIcon,
    "trending-up": ArrowTrendingUpIcon,
    underline: UnderlineIcon,
    unlock: LockOpenIcon,
    upload: ArrowUpTrayIcon,
    user: UserIcon,
    users: UsersIcon,
    volume: SpeakerWaveIcon,
    "volume-off": SpeakerXMarkIcon,
    wallet: WalletIcon,
    wand: SparklesIcon,
    wifi: WifiIcon,
    x: XMarkIcon,
    "x-circle": XCircleIcon,
    zap: BoltIcon,
    "zoom-in": MagnifyingGlassPlusIcon,
    "zoom-out": MagnifyingGlassMinusIcon,
  },
};

export default pack;
