/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as TrainersIdRouteImport } from './routes/trainers.$id'
import { Route as StudioStudioIdRouteImport } from './routes/studio.$studioId'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as MeSubscriptionsRouteImport } from './routes/me/subscriptions'
import { Route as MeProfileRouteImport } from './routes/me/profile'
import { Route as MeOnboardingRouteImport } from './routes/me/onboarding'
import { Route as MeJourneyRouteImport } from './routes/me/journey'
import { Route as MeInvoicesRouteImport } from './routes/me/invoices'
import { Route as MeFeedRouteImport } from './routes/me/feed'
import { Route as MeContestsRouteImport } from './routes/me/contests'
import { Route as MeCheckInRouteImport } from './routes/me/check-in'
import { Route as MeCalendarRouteImport } from './routes/me/calendar'
import { Route as MeBookingsRouteImport } from './routes/me/bookings'
import { Route as MeBookRouteImport } from './routes/me/book'
import { Route as MeAttendanceRouteImport } from './routes/me/attendance'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppRetentionRouteImport } from './routes/app/retention'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppInvoicesRouteImport } from './routes/app/invoices'
import { Route as AppFeedRouteImport } from './routes/app/feed'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as MeTrainersIndexRouteImport } from './routes/me/trainers/index'
import { Route as MeMessagesIndexRouteImport } from './routes/me/messages/index'
import { Route as MeLocationsIndexRouteImport } from './routes/me/locations/index'
import { Route as AppTrainersIndexRouteImport } from './routes/app/trainers/index'
import { Route as AppSubscriptionsIndexRouteImport } from './routes/app/subscriptions/index'
import { Route as AppStudentsIndexRouteImport } from './routes/app/students/index'
import { Route as AppMessagesIndexRouteImport } from './routes/app/messages/index'
import { Route as AppLocationsIndexRouteImport } from './routes/app/locations/index'
import { Route as AppExpensesIndexRouteImport } from './routes/app/expenses/index'
import { Route as AppContestsIndexRouteImport } from './routes/app/contests/index'
import { Route as AppCertificatesIndexRouteImport } from './routes/app/certificates/index'
import { Route as AppBookingsIndexRouteImport } from './routes/app/bookings/index'
import { Route as AppBatchesIndexRouteImport } from './routes/app/batches/index'
import { Route as MeProfileSecurityRouteImport } from './routes/me/profile_.security'
import { Route as MeProfileFollowRequestsRouteImport } from './routes/me/profile_.follow-requests'
import { Route as MeProfileEditRouteImport } from './routes/me/profile_.edit'
import { Route as MeProfileChangePasswordRouteImport } from './routes/me/profile_.change-password'
import { Route as MeProfileChangeEmailRouteImport } from './routes/me/profile_.change-email'
import { Route as MeMessagesIdRouteImport } from './routes/me/messages/$id'
import { Route as MeLocationsIdRouteImport } from './routes/me/locations/$id'
import { Route as MeCheckoutBookingIdRouteImport } from './routes/me/checkout/$bookingId'
import { Route as MeBatchesIdRouteImport } from './routes/me/batches/$id'
import { Route as AppTrainersNewRouteImport } from './routes/app/trainers/new'
import { Route as AppSubscriptionsNewRouteImport } from './routes/app/subscriptions/new'
import { Route as AppSubscriptionsIdRouteImport } from './routes/app/subscriptions/$id'
import { Route as AppStudentsNewRouteImport } from './routes/app/students/new'
import { Route as AppStudentsImportRouteImport } from './routes/app/students/import'
import { Route as AppStudentsIdRouteImport } from './routes/app/students/$id'
import { Route as AppSettingsTeamRouteImport } from './routes/app/settings_.team'
import { Route as AppSettingsStylesRouteImport } from './routes/app/settings_.styles'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings_.profile'
import { Route as AppSettingsPaymentsRouteImport } from './routes/app/settings_.payments'
import { Route as AppSettingsBrandingRouteImport } from './routes/app/settings_.branding'
import { Route as AppSettingsBillingRouteImport } from './routes/app/settings_.billing'
import { Route as AppProfileSecurityRouteImport } from './routes/app/profile_.security'
import { Route as AppProfileFollowRequestsRouteImport } from './routes/app/profile_.follow-requests'
import { Route as AppProfileEditRouteImport } from './routes/app/profile_.edit'
import { Route as AppProfileChangePasswordRouteImport } from './routes/app/profile_.change-password'
import { Route as AppProfileChangeEmailRouteImport } from './routes/app/profile_.change-email'
import { Route as AppMessagesIdRouteImport } from './routes/app/messages/$id'
import { Route as AppLocationsNewRouteImport } from './routes/app/locations/new'
import { Route as AppLocationsIdRouteImport } from './routes/app/locations/$id'
import { Route as AppExpensesReportsRouteImport } from './routes/app/expenses/reports'
import { Route as AppExpensesListRouteImport } from './routes/app/expenses/list'
import { Route as AppExpensesCategoriesRouteImport } from './routes/app/expenses/categories'
import { Route as AppContestsNewRouteImport } from './routes/app/contests/new'
import { Route as AppContestsIdRouteImport } from './routes/app/contests/$id'
import { Route as AppCertificatesNewRouteImport } from './routes/app/certificates/new'
import { Route as AppCertificatesIdRouteImport } from './routes/app/certificates/$id'
import { Route as AppBatchesNewRouteImport } from './routes/app/batches/new'
import { Route as AppBatchesIdRouteImport } from './routes/app/batches/$id'
import { Route as AdminStudiosNewRouteImport } from './routes/admin/studios/new'
import { Route as AdminStudiosIdRouteImport } from './routes/admin/studios/$id'
import { Route as MeLocationsIdClassesRouteImport } from './routes/me/locations/$id_.classes'
import { Route as MeCheckoutInvoiceInvoiceIdRouteImport } from './routes/me/checkout/invoice.$invoiceId'
import { Route as AppSessionsIdAttendanceRouteImport } from './routes/app/sessions.$id.attendance'
import { Route as AppLocationsIdEditRouteImport } from './routes/app/locations/$id_.edit'
import { Route as AppLocationsIdClassesRouteImport } from './routes/app/locations/$id_.classes'
import { Route as AppBatchesIdSettingsRouteImport } from './routes/app/batches/$id_.settings'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersIdRoute = TrainersIdRouteImport.update({
  id: '/trainers/$id',
  path: '/trainers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioStudioIdRoute = StudioStudioIdRouteImport.update({
  id: '/studio/$studioId',
  path: '/studio/$studioId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSubscriptionsRoute = MeSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => MeRoute,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MeRoute,
} as any)
const MeOnboardingRoute = MeOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => MeRoute,
} as any)
const MeJourneyRoute = MeJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => MeRoute,
} as any)
const MeInvoicesRoute = MeInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => MeRoute,
} as any)
const MeFeedRoute = MeFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => MeRoute,
} as any)
const MeContestsRoute = MeContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => MeRoute,
} as any)
const MeCheckInRoute = MeCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => MeRoute,
} as any)
const MeCalendarRoute = MeCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => MeRoute,
} as any)
const MeBookingsRoute = MeBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => MeRoute,
} as any)
const MeBookRoute = MeBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => MeRoute,
} as any)
const MeAttendanceRoute = MeAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => MeRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRetentionRoute = AppRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const MeTrainersIndexRoute = MeTrainersIndexRouteImport.update({
  id: '/trainers/',
  path: '/trainers/',
  getParentRoute: () => MeRoute,
} as any)
const MeMessagesIndexRoute = MeMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => MeRoute,
} as any)
const MeLocationsIndexRoute = MeLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => MeRoute,
} as any)
const AppTrainersIndexRoute = AppTrainersIndexRouteImport.update({
  id: '/trainers/',
  path: '/trainers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsIndexRoute = AppSubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIndexRoute = AppLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppContestsIndexRoute = AppContestsIndexRouteImport.update({
  id: '/contests/',
  path: '/contests/',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesIndexRoute = AppCertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIndexRoute = AppBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AppRoute,
} as any)
const MeProfileSecurityRoute = MeProfileSecurityRouteImport.update({
  id: '/profile_/security',
  path: '/profile/security',
  getParentRoute: () => MeRoute,
} as any)
const MeProfileFollowRequestsRoute = MeProfileFollowRequestsRouteImport.update({
  id: '/profile_/follow-requests',
  path: '/profile/follow-requests',
  getParentRoute: () => MeRoute,
} as any)
const MeProfileEditRoute = MeProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => MeRoute,
} as any)
const MeProfileChangePasswordRoute = MeProfileChangePasswordRouteImport.update({
  id: '/profile_/change-password',
  path: '/profile/change-password',
  getParentRoute: () => MeRoute,
} as any)
const MeProfileChangeEmailRoute = MeProfileChangeEmailRouteImport.update({
  id: '/profile_/change-email',
  path: '/profile/change-email',
  getParentRoute: () => MeRoute,
} as any)
const MeMessagesIdRoute = MeMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => MeRoute,
} as any)
const MeLocationsIdRoute = MeLocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => MeRoute,
} as any)
const MeCheckoutBookingIdRoute = MeCheckoutBookingIdRouteImport.update({
  id: '/checkout/$bookingId',
  path: '/checkout/$bookingId',
  getParentRoute: () => MeRoute,
} as any)
const MeBatchesIdRoute = MeBatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => MeRoute,
} as any)
const AppTrainersNewRoute = AppTrainersNewRouteImport.update({
  id: '/trainers/new',
  path: '/trainers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsNewRoute = AppSubscriptionsNewRouteImport.update({
  id: '/subscriptions/new',
  path: '/subscriptions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsIdRoute = AppSubscriptionsIdRouteImport.update({
  id: '/subscriptions/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsNewRoute = AppStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsImportRoute = AppStudentsImportRouteImport.update({
  id: '/students/import',
  path: '/students/import',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIdRoute = AppStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings_/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsStylesRoute = AppSettingsStylesRouteImport.update({
  id: '/settings_/styles',
  path: '/settings/styles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/settings_/profile',
  path: '/settings/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPaymentsRoute = AppSettingsPaymentsRouteImport.update({
  id: '/settings_/payments',
  path: '/settings/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBrandingRoute = AppSettingsBrandingRouteImport.update({
  id: '/settings_/branding',
  path: '/settings/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings_/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileSecurityRoute = AppProfileSecurityRouteImport.update({
  id: '/profile_/security',
  path: '/profile/security',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileFollowRequestsRoute =
  AppProfileFollowRequestsRouteImport.update({
    id: '/profile_/follow-requests',
    path: '/profile/follow-requests',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileChangePasswordRoute =
  AppProfileChangePasswordRouteImport.update({
    id: '/profile_/change-password',
    path: '/profile/change-password',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfileChangeEmailRoute = AppProfileChangeEmailRouteImport.update({
  id: '/profile_/change-email',
  path: '/profile/change-email',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIdRoute = AppMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsNewRoute = AppLocationsNewRouteImport.update({
  id: '/locations/new',
  path: '/locations/new',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIdRoute = AppLocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesReportsRoute = AppExpensesReportsRouteImport.update({
  id: '/expenses/reports',
  path: '/expenses/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesListRoute = AppExpensesListRouteImport.update({
  id: '/expenses/list',
  path: '/expenses/list',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesCategoriesRoute = AppExpensesCategoriesRouteImport.update({
  id: '/expenses/categories',
  path: '/expenses/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppContestsNewRoute = AppContestsNewRouteImport.update({
  id: '/contests/new',
  path: '/contests/new',
  getParentRoute: () => AppRoute,
} as any)
const AppContestsIdRoute = AppContestsIdRouteImport.update({
  id: '/contests/$id',
  path: '/contests/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesNewRoute = AppCertificatesNewRouteImport.update({
  id: '/certificates/new',
  path: '/certificates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesIdRoute = AppCertificatesIdRouteImport.update({
  id: '/certificates/$id',
  path: '/certificates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesNewRoute = AppBatchesNewRouteImport.update({
  id: '/batches/new',
  path: '/batches/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIdRoute = AppBatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => AppRoute,
} as any)
const AdminStudiosNewRoute = AdminStudiosNewRouteImport.update({
  id: '/studios/new',
  path: '/studios/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudiosIdRoute = AdminStudiosIdRouteImport.update({
  id: '/studios/$id',
  path: '/studios/$id',
  getParentRoute: () => AdminRoute,
} as any)
const MeLocationsIdClassesRoute = MeLocationsIdClassesRouteImport.update({
  id: '/locations/$id_/classes',
  path: '/locations/$id/classes',
  getParentRoute: () => MeRoute,
} as any)
const MeCheckoutInvoiceInvoiceIdRoute =
  MeCheckoutInvoiceInvoiceIdRouteImport.update({
    id: '/checkout/invoice/$invoiceId',
    path: '/checkout/invoice/$invoiceId',
    getParentRoute: () => MeRoute,
  } as any)
const AppSessionsIdAttendanceRoute = AppSessionsIdAttendanceRouteImport.update({
  id: '/sessions/$id/attendance',
  path: '/sessions/$id/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIdEditRoute = AppLocationsIdEditRouteImport.update({
  id: '/locations/$id_/edit',
  path: '/locations/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIdClassesRoute = AppLocationsIdClassesRouteImport.update({
  id: '/locations/$id_/classes',
  path: '/locations/$id/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIdSettingsRoute = AppBatchesIdSettingsRouteImport.update({
  id: '/batches/$id_/settings',
  path: '/batches/$id/settings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/profile': typeof AdminProfileRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/feed': typeof AppFeedRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/retention': typeof AppRetentionRoute
  '/app/settings': typeof AppSettingsRoute
  '/me/attendance': typeof MeAttendanceRoute
  '/me/book': typeof MeBookRoute
  '/me/bookings': typeof MeBookingsRoute
  '/me/calendar': typeof MeCalendarRoute
  '/me/check-in': typeof MeCheckInRoute
  '/me/contests': typeof MeContestsRoute
  '/me/feed': typeof MeFeedRoute
  '/me/invoices': typeof MeInvoicesRoute
  '/me/journey': typeof MeJourneyRoute
  '/me/onboarding': typeof MeOnboardingRoute
  '/me/profile': typeof MeProfileRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/posts/$id': typeof PostsIdRoute
  '/studio/$studioId': typeof StudioStudioIdRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/users/$id': typeof UsersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/me/': typeof MeIndexRoute
  '/admin/studios/$id': typeof AdminStudiosIdRoute
  '/admin/studios/new': typeof AdminStudiosNewRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/batches/new': typeof AppBatchesNewRoute
  '/app/certificates/$id': typeof AppCertificatesIdRoute
  '/app/certificates/new': typeof AppCertificatesNewRoute
  '/app/contests/$id': typeof AppContestsIdRoute
  '/app/contests/new': typeof AppContestsNewRoute
  '/app/expenses/categories': typeof AppExpensesCategoriesRoute
  '/app/expenses/list': typeof AppExpensesListRoute
  '/app/expenses/reports': typeof AppExpensesReportsRoute
  '/app/locations/$id': typeof AppLocationsIdRoute
  '/app/locations/new': typeof AppLocationsNewRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/profile/change-email': typeof AppProfileChangeEmailRoute
  '/app/profile/change-password': typeof AppProfileChangePasswordRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/follow-requests': typeof AppProfileFollowRequestsRoute
  '/app/profile/security': typeof AppProfileSecurityRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/branding': typeof AppSettingsBrandingRoute
  '/app/settings/payments': typeof AppSettingsPaymentsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/styles': typeof AppSettingsStylesRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/students/$id': typeof AppStudentsIdRoute
  '/app/students/import': typeof AppStudentsImportRoute
  '/app/students/new': typeof AppStudentsNewRoute
  '/app/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/app/subscriptions/new': typeof AppSubscriptionsNewRoute
  '/app/trainers/new': typeof AppTrainersNewRoute
  '/me/batches/$id': typeof MeBatchesIdRoute
  '/me/checkout/$bookingId': typeof MeCheckoutBookingIdRoute
  '/me/locations/$id': typeof MeLocationsIdRoute
  '/me/messages/$id': typeof MeMessagesIdRoute
  '/me/profile/change-email': typeof MeProfileChangeEmailRoute
  '/me/profile/change-password': typeof MeProfileChangePasswordRoute
  '/me/profile/edit': typeof MeProfileEditRoute
  '/me/profile/follow-requests': typeof MeProfileFollowRequestsRoute
  '/me/profile/security': typeof MeProfileSecurityRoute
  '/app/batches/': typeof AppBatchesIndexRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
  '/app/certificates/': typeof AppCertificatesIndexRoute
  '/app/contests/': typeof AppContestsIndexRoute
  '/app/expenses/': typeof AppExpensesIndexRoute
  '/app/locations/': typeof AppLocationsIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
  '/app/subscriptions/': typeof AppSubscriptionsIndexRoute
  '/app/trainers/': typeof AppTrainersIndexRoute
  '/me/locations/': typeof MeLocationsIndexRoute
  '/me/messages/': typeof MeMessagesIndexRoute
  '/me/trainers/': typeof MeTrainersIndexRoute
  '/app/batches/$id/settings': typeof AppBatchesIdSettingsRoute
  '/app/locations/$id/classes': typeof AppLocationsIdClassesRoute
  '/app/locations/$id/edit': typeof AppLocationsIdEditRoute
  '/app/sessions/$id/attendance': typeof AppSessionsIdAttendanceRoute
  '/me/checkout/invoice/$invoiceId': typeof MeCheckoutInvoiceInvoiceIdRoute
  '/me/locations/$id/classes': typeof MeLocationsIdClassesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/profile': typeof AdminProfileRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/feed': typeof AppFeedRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/retention': typeof AppRetentionRoute
  '/app/settings': typeof AppSettingsRoute
  '/me/attendance': typeof MeAttendanceRoute
  '/me/book': typeof MeBookRoute
  '/me/bookings': typeof MeBookingsRoute
  '/me/calendar': typeof MeCalendarRoute
  '/me/check-in': typeof MeCheckInRoute
  '/me/contests': typeof MeContestsRoute
  '/me/feed': typeof MeFeedRoute
  '/me/invoices': typeof MeInvoicesRoute
  '/me/journey': typeof MeJourneyRoute
  '/me/onboarding': typeof MeOnboardingRoute
  '/me/profile': typeof MeProfileRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/posts/$id': typeof PostsIdRoute
  '/studio/$studioId': typeof StudioStudioIdRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/users/$id': typeof UsersIdRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/me': typeof MeIndexRoute
  '/admin/studios/$id': typeof AdminStudiosIdRoute
  '/admin/studios/new': typeof AdminStudiosNewRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/batches/new': typeof AppBatchesNewRoute
  '/app/certificates/$id': typeof AppCertificatesIdRoute
  '/app/certificates/new': typeof AppCertificatesNewRoute
  '/app/contests/$id': typeof AppContestsIdRoute
  '/app/contests/new': typeof AppContestsNewRoute
  '/app/expenses/categories': typeof AppExpensesCategoriesRoute
  '/app/expenses/list': typeof AppExpensesListRoute
  '/app/expenses/reports': typeof AppExpensesReportsRoute
  '/app/locations/$id': typeof AppLocationsIdRoute
  '/app/locations/new': typeof AppLocationsNewRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/profile/change-email': typeof AppProfileChangeEmailRoute
  '/app/profile/change-password': typeof AppProfileChangePasswordRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/follow-requests': typeof AppProfileFollowRequestsRoute
  '/app/profile/security': typeof AppProfileSecurityRoute
  '/app/settings/billing': typeof AppSettingsBillingRoute
  '/app/settings/branding': typeof AppSettingsBrandingRoute
  '/app/settings/payments': typeof AppSettingsPaymentsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/styles': typeof AppSettingsStylesRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/students/$id': typeof AppStudentsIdRoute
  '/app/students/import': typeof AppStudentsImportRoute
  '/app/students/new': typeof AppStudentsNewRoute
  '/app/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/app/subscriptions/new': typeof AppSubscriptionsNewRoute
  '/app/trainers/new': typeof AppTrainersNewRoute
  '/me/batches/$id': typeof MeBatchesIdRoute
  '/me/checkout/$bookingId': typeof MeCheckoutBookingIdRoute
  '/me/locations/$id': typeof MeLocationsIdRoute
  '/me/messages/$id': typeof MeMessagesIdRoute
  '/me/profile/change-email': typeof MeProfileChangeEmailRoute
  '/me/profile/change-password': typeof MeProfileChangePasswordRoute
  '/me/profile/edit': typeof MeProfileEditRoute
  '/me/profile/follow-requests': typeof MeProfileFollowRequestsRoute
  '/me/profile/security': typeof MeProfileSecurityRoute
  '/app/batches': typeof AppBatchesIndexRoute
  '/app/bookings': typeof AppBookingsIndexRoute
  '/app/certificates': typeof AppCertificatesIndexRoute
  '/app/contests': typeof AppContestsIndexRoute
  '/app/expenses': typeof AppExpensesIndexRoute
  '/app/locations': typeof AppLocationsIndexRoute
  '/app/messages': typeof AppMessagesIndexRoute
  '/app/students': typeof AppStudentsIndexRoute
  '/app/subscriptions': typeof AppSubscriptionsIndexRoute
  '/app/trainers': typeof AppTrainersIndexRoute
  '/me/locations': typeof MeLocationsIndexRoute
  '/me/messages': typeof MeMessagesIndexRoute
  '/me/trainers': typeof MeTrainersIndexRoute
  '/app/batches/$id/settings': typeof AppBatchesIdSettingsRoute
  '/app/locations/$id/classes': typeof AppLocationsIdClassesRoute
  '/app/locations/$id/edit': typeof AppLocationsIdEditRoute
  '/app/sessions/$id/attendance': typeof AppSessionsIdAttendanceRoute
  '/me/checkout/invoice/$invoiceId': typeof MeCheckoutInvoiceInvoiceIdRoute
  '/me/locations/$id/classes': typeof MeLocationsIdClassesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/profile': typeof AdminProfileRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/feed': typeof AppFeedRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/retention': typeof AppRetentionRoute
  '/app/settings': typeof AppSettingsRoute
  '/me/attendance': typeof MeAttendanceRoute
  '/me/book': typeof MeBookRoute
  '/me/bookings': typeof MeBookingsRoute
  '/me/calendar': typeof MeCalendarRoute
  '/me/check-in': typeof MeCheckInRoute
  '/me/contests': typeof MeContestsRoute
  '/me/feed': typeof MeFeedRoute
  '/me/invoices': typeof MeInvoicesRoute
  '/me/journey': typeof MeJourneyRoute
  '/me/onboarding': typeof MeOnboardingRoute
  '/me/profile': typeof MeProfileRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/posts/$id': typeof PostsIdRoute
  '/studio/$studioId': typeof StudioStudioIdRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/users/$id': typeof UsersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/me/': typeof MeIndexRoute
  '/admin/studios/$id': typeof AdminStudiosIdRoute
  '/admin/studios/new': typeof AdminStudiosNewRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/batches/new': typeof AppBatchesNewRoute
  '/app/certificates/$id': typeof AppCertificatesIdRoute
  '/app/certificates/new': typeof AppCertificatesNewRoute
  '/app/contests/$id': typeof AppContestsIdRoute
  '/app/contests/new': typeof AppContestsNewRoute
  '/app/expenses/categories': typeof AppExpensesCategoriesRoute
  '/app/expenses/list': typeof AppExpensesListRoute
  '/app/expenses/reports': typeof AppExpensesReportsRoute
  '/app/locations/$id': typeof AppLocationsIdRoute
  '/app/locations/new': typeof AppLocationsNewRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/profile_/change-email': typeof AppProfileChangeEmailRoute
  '/app/profile_/change-password': typeof AppProfileChangePasswordRoute
  '/app/profile_/edit': typeof AppProfileEditRoute
  '/app/profile_/follow-requests': typeof AppProfileFollowRequestsRoute
  '/app/profile_/security': typeof AppProfileSecurityRoute
  '/app/settings_/billing': typeof AppSettingsBillingRoute
  '/app/settings_/branding': typeof AppSettingsBrandingRoute
  '/app/settings_/payments': typeof AppSettingsPaymentsRoute
  '/app/settings_/profile': typeof AppSettingsProfileRoute
  '/app/settings_/styles': typeof AppSettingsStylesRoute
  '/app/settings_/team': typeof AppSettingsTeamRoute
  '/app/students/$id': typeof AppStudentsIdRoute
  '/app/students/import': typeof AppStudentsImportRoute
  '/app/students/new': typeof AppStudentsNewRoute
  '/app/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/app/subscriptions/new': typeof AppSubscriptionsNewRoute
  '/app/trainers/new': typeof AppTrainersNewRoute
  '/me/batches/$id': typeof MeBatchesIdRoute
  '/me/checkout/$bookingId': typeof MeCheckoutBookingIdRoute
  '/me/locations/$id': typeof MeLocationsIdRoute
  '/me/messages/$id': typeof MeMessagesIdRoute
  '/me/profile_/change-email': typeof MeProfileChangeEmailRoute
  '/me/profile_/change-password': typeof MeProfileChangePasswordRoute
  '/me/profile_/edit': typeof MeProfileEditRoute
  '/me/profile_/follow-requests': typeof MeProfileFollowRequestsRoute
  '/me/profile_/security': typeof MeProfileSecurityRoute
  '/app/batches/': typeof AppBatchesIndexRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
  '/app/certificates/': typeof AppCertificatesIndexRoute
  '/app/contests/': typeof AppContestsIndexRoute
  '/app/expenses/': typeof AppExpensesIndexRoute
  '/app/locations/': typeof AppLocationsIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
  '/app/subscriptions/': typeof AppSubscriptionsIndexRoute
  '/app/trainers/': typeof AppTrainersIndexRoute
  '/me/locations/': typeof MeLocationsIndexRoute
  '/me/messages/': typeof MeMessagesIndexRoute
  '/me/trainers/': typeof MeTrainersIndexRoute
  '/app/batches/$id_/settings': typeof AppBatchesIdSettingsRoute
  '/app/locations/$id_/classes': typeof AppLocationsIdClassesRoute
  '/app/locations/$id_/edit': typeof AppLocationsIdEditRoute
  '/app/sessions/$id/attendance': typeof AppSessionsIdAttendanceRoute
  '/me/checkout/invoice/$invoiceId': typeof MeCheckoutInvoiceInvoiceIdRoute
  '/me/locations/$id_/classes': typeof MeLocationsIdClassesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/me'
    | '/register'
    | '/admin/profile'
    | '/app/calendar'
    | '/app/feed'
    | '/app/invoices'
    | '/app/payments'
    | '/app/profile'
    | '/app/retention'
    | '/app/settings'
    | '/me/attendance'
    | '/me/book'
    | '/me/bookings'
    | '/me/calendar'
    | '/me/check-in'
    | '/me/contests'
    | '/me/feed'
    | '/me/invoices'
    | '/me/journey'
    | '/me/onboarding'
    | '/me/profile'
    | '/me/subscriptions'
    | '/posts/$id'
    | '/studio/$studioId'
    | '/trainers/$id'
    | '/users/$id'
    | '/admin/'
    | '/app/'
    | '/me/'
    | '/admin/studios/$id'
    | '/admin/studios/new'
    | '/app/batches/$id'
    | '/app/batches/new'
    | '/app/certificates/$id'
    | '/app/certificates/new'
    | '/app/contests/$id'
    | '/app/contests/new'
    | '/app/expenses/categories'
    | '/app/expenses/list'
    | '/app/expenses/reports'
    | '/app/locations/$id'
    | '/app/locations/new'
    | '/app/messages/$id'
    | '/app/profile/change-email'
    | '/app/profile/change-password'
    | '/app/profile/edit'
    | '/app/profile/follow-requests'
    | '/app/profile/security'
    | '/app/settings/billing'
    | '/app/settings/branding'
    | '/app/settings/payments'
    | '/app/settings/profile'
    | '/app/settings/styles'
    | '/app/settings/team'
    | '/app/students/$id'
    | '/app/students/import'
    | '/app/students/new'
    | '/app/subscriptions/$id'
    | '/app/subscriptions/new'
    | '/app/trainers/new'
    | '/me/batches/$id'
    | '/me/checkout/$bookingId'
    | '/me/locations/$id'
    | '/me/messages/$id'
    | '/me/profile/change-email'
    | '/me/profile/change-password'
    | '/me/profile/edit'
    | '/me/profile/follow-requests'
    | '/me/profile/security'
    | '/app/batches/'
    | '/app/bookings/'
    | '/app/certificates/'
    | '/app/contests/'
    | '/app/expenses/'
    | '/app/locations/'
    | '/app/messages/'
    | '/app/students/'
    | '/app/subscriptions/'
    | '/app/trainers/'
    | '/me/locations/'
    | '/me/messages/'
    | '/me/trainers/'
    | '/app/batches/$id/settings'
    | '/app/locations/$id/classes'
    | '/app/locations/$id/edit'
    | '/app/sessions/$id/attendance'
    | '/me/checkout/invoice/$invoiceId'
    | '/me/locations/$id/classes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/register'
    | '/admin/profile'
    | '/app/calendar'
    | '/app/feed'
    | '/app/invoices'
    | '/app/payments'
    | '/app/profile'
    | '/app/retention'
    | '/app/settings'
    | '/me/attendance'
    | '/me/book'
    | '/me/bookings'
    | '/me/calendar'
    | '/me/check-in'
    | '/me/contests'
    | '/me/feed'
    | '/me/invoices'
    | '/me/journey'
    | '/me/onboarding'
    | '/me/profile'
    | '/me/subscriptions'
    | '/posts/$id'
    | '/studio/$studioId'
    | '/trainers/$id'
    | '/users/$id'
    | '/admin'
    | '/app'
    | '/me'
    | '/admin/studios/$id'
    | '/admin/studios/new'
    | '/app/batches/$id'
    | '/app/batches/new'
    | '/app/certificates/$id'
    | '/app/certificates/new'
    | '/app/contests/$id'
    | '/app/contests/new'
    | '/app/expenses/categories'
    | '/app/expenses/list'
    | '/app/expenses/reports'
    | '/app/locations/$id'
    | '/app/locations/new'
    | '/app/messages/$id'
    | '/app/profile/change-email'
    | '/app/profile/change-password'
    | '/app/profile/edit'
    | '/app/profile/follow-requests'
    | '/app/profile/security'
    | '/app/settings/billing'
    | '/app/settings/branding'
    | '/app/settings/payments'
    | '/app/settings/profile'
    | '/app/settings/styles'
    | '/app/settings/team'
    | '/app/students/$id'
    | '/app/students/import'
    | '/app/students/new'
    | '/app/subscriptions/$id'
    | '/app/subscriptions/new'
    | '/app/trainers/new'
    | '/me/batches/$id'
    | '/me/checkout/$bookingId'
    | '/me/locations/$id'
    | '/me/messages/$id'
    | '/me/profile/change-email'
    | '/me/profile/change-password'
    | '/me/profile/edit'
    | '/me/profile/follow-requests'
    | '/me/profile/security'
    | '/app/batches'
    | '/app/bookings'
    | '/app/certificates'
    | '/app/contests'
    | '/app/expenses'
    | '/app/locations'
    | '/app/messages'
    | '/app/students'
    | '/app/subscriptions'
    | '/app/trainers'
    | '/me/locations'
    | '/me/messages'
    | '/me/trainers'
    | '/app/batches/$id/settings'
    | '/app/locations/$id/classes'
    | '/app/locations/$id/edit'
    | '/app/sessions/$id/attendance'
    | '/me/checkout/invoice/$invoiceId'
    | '/me/locations/$id/classes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/me'
    | '/register'
    | '/admin/profile'
    | '/app/calendar'
    | '/app/feed'
    | '/app/invoices'
    | '/app/payments'
    | '/app/profile'
    | '/app/retention'
    | '/app/settings'
    | '/me/attendance'
    | '/me/book'
    | '/me/bookings'
    | '/me/calendar'
    | '/me/check-in'
    | '/me/contests'
    | '/me/feed'
    | '/me/invoices'
    | '/me/journey'
    | '/me/onboarding'
    | '/me/profile'
    | '/me/subscriptions'
    | '/posts/$id'
    | '/studio/$studioId'
    | '/trainers/$id'
    | '/users/$id'
    | '/admin/'
    | '/app/'
    | '/me/'
    | '/admin/studios/$id'
    | '/admin/studios/new'
    | '/app/batches/$id'
    | '/app/batches/new'
    | '/app/certificates/$id'
    | '/app/certificates/new'
    | '/app/contests/$id'
    | '/app/contests/new'
    | '/app/expenses/categories'
    | '/app/expenses/list'
    | '/app/expenses/reports'
    | '/app/locations/$id'
    | '/app/locations/new'
    | '/app/messages/$id'
    | '/app/profile_/change-email'
    | '/app/profile_/change-password'
    | '/app/profile_/edit'
    | '/app/profile_/follow-requests'
    | '/app/profile_/security'
    | '/app/settings_/billing'
    | '/app/settings_/branding'
    | '/app/settings_/payments'
    | '/app/settings_/profile'
    | '/app/settings_/styles'
    | '/app/settings_/team'
    | '/app/students/$id'
    | '/app/students/import'
    | '/app/students/new'
    | '/app/subscriptions/$id'
    | '/app/subscriptions/new'
    | '/app/trainers/new'
    | '/me/batches/$id'
    | '/me/checkout/$bookingId'
    | '/me/locations/$id'
    | '/me/messages/$id'
    | '/me/profile_/change-email'
    | '/me/profile_/change-password'
    | '/me/profile_/edit'
    | '/me/profile_/follow-requests'
    | '/me/profile_/security'
    | '/app/batches/'
    | '/app/bookings/'
    | '/app/certificates/'
    | '/app/contests/'
    | '/app/expenses/'
    | '/app/locations/'
    | '/app/messages/'
    | '/app/students/'
    | '/app/subscriptions/'
    | '/app/trainers/'
    | '/me/locations/'
    | '/me/messages/'
    | '/me/trainers/'
    | '/app/batches/$id_/settings'
    | '/app/locations/$id_/classes'
    | '/app/locations/$id_/edit'
    | '/app/sessions/$id/attendance'
    | '/me/checkout/invoice/$invoiceId'
    | '/me/locations/$id_/classes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  PostsIdRoute: typeof PostsIdRoute
  StudioStudioIdRoute: typeof StudioStudioIdRoute
  TrainersIdRoute: typeof TrainersIdRoute
  UsersIdRoute: typeof UsersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/$id': {
      id: '/trainers/$id'
      path: '/trainers/$id'
      fullPath: '/trainers/$id'
      preLoaderRoute: typeof TrainersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$studioId': {
      id: '/studio/$studioId'
      path: '/studio/$studioId'
      fullPath: '/studio/$studioId'
      preLoaderRoute: typeof StudioStudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/subscriptions': {
      id: '/me/subscriptions'
      path: '/subscriptions'
      fullPath: '/me/subscriptions'
      preLoaderRoute: typeof MeSubscriptionsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/onboarding': {
      id: '/me/onboarding'
      path: '/onboarding'
      fullPath: '/me/onboarding'
      preLoaderRoute: typeof MeOnboardingRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/journey': {
      id: '/me/journey'
      path: '/journey'
      fullPath: '/me/journey'
      preLoaderRoute: typeof MeJourneyRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/invoices': {
      id: '/me/invoices'
      path: '/invoices'
      fullPath: '/me/invoices'
      preLoaderRoute: typeof MeInvoicesRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/feed': {
      id: '/me/feed'
      path: '/feed'
      fullPath: '/me/feed'
      preLoaderRoute: typeof MeFeedRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/contests': {
      id: '/me/contests'
      path: '/contests'
      fullPath: '/me/contests'
      preLoaderRoute: typeof MeContestsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/check-in': {
      id: '/me/check-in'
      path: '/check-in'
      fullPath: '/me/check-in'
      preLoaderRoute: typeof MeCheckInRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/calendar': {
      id: '/me/calendar'
      path: '/calendar'
      fullPath: '/me/calendar'
      preLoaderRoute: typeof MeCalendarRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/bookings': {
      id: '/me/bookings'
      path: '/bookings'
      fullPath: '/me/bookings'
      preLoaderRoute: typeof MeBookingsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/book': {
      id: '/me/book'
      path: '/book'
      fullPath: '/me/book'
      preLoaderRoute: typeof MeBookRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/attendance': {
      id: '/me/attendance'
      path: '/attendance'
      fullPath: '/me/attendance'
      preLoaderRoute: typeof MeAttendanceRouteImport
      parentRoute: typeof MeRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/retention': {
      id: '/app/retention'
      path: '/retention'
      fullPath: '/app/retention'
      preLoaderRoute: typeof AppRetentionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/me/trainers/': {
      id: '/me/trainers/'
      path: '/trainers'
      fullPath: '/me/trainers/'
      preLoaderRoute: typeof MeTrainersIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/messages/': {
      id: '/me/messages/'
      path: '/messages'
      fullPath: '/me/messages/'
      preLoaderRoute: typeof MeMessagesIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/locations/': {
      id: '/me/locations/'
      path: '/locations'
      fullPath: '/me/locations/'
      preLoaderRoute: typeof MeLocationsIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/app/trainers/': {
      id: '/app/trainers/'
      path: '/trainers'
      fullPath: '/app/trainers/'
      preLoaderRoute: typeof AppTrainersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions/': {
      id: '/app/subscriptions/'
      path: '/subscriptions'
      fullPath: '/app/subscriptions/'
      preLoaderRoute: typeof AppSubscriptionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/': {
      id: '/app/students/'
      path: '/students'
      fullPath: '/app/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/': {
      id: '/app/messages/'
      path: '/messages'
      fullPath: '/app/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations/': {
      id: '/app/locations/'
      path: '/locations'
      fullPath: '/app/locations/'
      preLoaderRoute: typeof AppLocationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses/': {
      id: '/app/expenses/'
      path: '/expenses'
      fullPath: '/app/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contests/': {
      id: '/app/contests/'
      path: '/contests'
      fullPath: '/app/contests/'
      preLoaderRoute: typeof AppContestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates/': {
      id: '/app/certificates/'
      path: '/certificates'
      fullPath: '/app/certificates/'
      preLoaderRoute: typeof AppCertificatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings/': {
      id: '/app/bookings/'
      path: '/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/': {
      id: '/app/batches/'
      path: '/batches'
      fullPath: '/app/batches/'
      preLoaderRoute: typeof AppBatchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/me/profile_/security': {
      id: '/me/profile_/security'
      path: '/profile/security'
      fullPath: '/me/profile/security'
      preLoaderRoute: typeof MeProfileSecurityRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/profile_/follow-requests': {
      id: '/me/profile_/follow-requests'
      path: '/profile/follow-requests'
      fullPath: '/me/profile/follow-requests'
      preLoaderRoute: typeof MeProfileFollowRequestsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/profile_/edit': {
      id: '/me/profile_/edit'
      path: '/profile/edit'
      fullPath: '/me/profile/edit'
      preLoaderRoute: typeof MeProfileEditRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/profile_/change-password': {
      id: '/me/profile_/change-password'
      path: '/profile/change-password'
      fullPath: '/me/profile/change-password'
      preLoaderRoute: typeof MeProfileChangePasswordRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/profile_/change-email': {
      id: '/me/profile_/change-email'
      path: '/profile/change-email'
      fullPath: '/me/profile/change-email'
      preLoaderRoute: typeof MeProfileChangeEmailRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/messages/$id': {
      id: '/me/messages/$id'
      path: '/messages/$id'
      fullPath: '/me/messages/$id'
      preLoaderRoute: typeof MeMessagesIdRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/locations/$id': {
      id: '/me/locations/$id'
      path: '/locations/$id'
      fullPath: '/me/locations/$id'
      preLoaderRoute: typeof MeLocationsIdRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/checkout/$bookingId': {
      id: '/me/checkout/$bookingId'
      path: '/checkout/$bookingId'
      fullPath: '/me/checkout/$bookingId'
      preLoaderRoute: typeof MeCheckoutBookingIdRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/batches/$id': {
      id: '/me/batches/$id'
      path: '/batches/$id'
      fullPath: '/me/batches/$id'
      preLoaderRoute: typeof MeBatchesIdRouteImport
      parentRoute: typeof MeRoute
    }
    '/app/trainers/new': {
      id: '/app/trainers/new'
      path: '/trainers/new'
      fullPath: '/app/trainers/new'
      preLoaderRoute: typeof AppTrainersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions/new': {
      id: '/app/subscriptions/new'
      path: '/subscriptions/new'
      fullPath: '/app/subscriptions/new'
      preLoaderRoute: typeof AppSubscriptionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions/$id': {
      id: '/app/subscriptions/$id'
      path: '/subscriptions/$id'
      fullPath: '/app/subscriptions/$id'
      preLoaderRoute: typeof AppSubscriptionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/new': {
      id: '/app/students/new'
      path: '/students/new'
      fullPath: '/app/students/new'
      preLoaderRoute: typeof AppStudentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/import': {
      id: '/app/students/import'
      path: '/students/import'
      fullPath: '/app/students/import'
      preLoaderRoute: typeof AppStudentsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/$id': {
      id: '/app/students/$id'
      path: '/students/$id'
      fullPath: '/app/students/$id'
      preLoaderRoute: typeof AppStudentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings_/team': {
      id: '/app/settings_/team'
      path: '/settings/team'
      fullPath: '/app/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings_/styles': {
      id: '/app/settings_/styles'
      path: '/settings/styles'
      fullPath: '/app/settings/styles'
      preLoaderRoute: typeof AppSettingsStylesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings_/profile': {
      id: '/app/settings_/profile'
      path: '/settings/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings_/payments': {
      id: '/app/settings_/payments'
      path: '/settings/payments'
      fullPath: '/app/settings/payments'
      preLoaderRoute: typeof AppSettingsPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings_/branding': {
      id: '/app/settings_/branding'
      path: '/settings/branding'
      fullPath: '/app/settings/branding'
      preLoaderRoute: typeof AppSettingsBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings_/billing': {
      id: '/app/settings_/billing'
      path: '/settings/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile_/security': {
      id: '/app/profile_/security'
      path: '/profile/security'
      fullPath: '/app/profile/security'
      preLoaderRoute: typeof AppProfileSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile_/follow-requests': {
      id: '/app/profile_/follow-requests'
      path: '/profile/follow-requests'
      fullPath: '/app/profile/follow-requests'
      preLoaderRoute: typeof AppProfileFollowRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile_/edit': {
      id: '/app/profile_/edit'
      path: '/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile_/change-password': {
      id: '/app/profile_/change-password'
      path: '/profile/change-password'
      fullPath: '/app/profile/change-password'
      preLoaderRoute: typeof AppProfileChangePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile_/change-email': {
      id: '/app/profile_/change-email'
      path: '/profile/change-email'
      fullPath: '/app/profile/change-email'
      preLoaderRoute: typeof AppProfileChangeEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/$id': {
      id: '/app/messages/$id'
      path: '/messages/$id'
      fullPath: '/app/messages/$id'
      preLoaderRoute: typeof AppMessagesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations/new': {
      id: '/app/locations/new'
      path: '/locations/new'
      fullPath: '/app/locations/new'
      preLoaderRoute: typeof AppLocationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations/$id': {
      id: '/app/locations/$id'
      path: '/locations/$id'
      fullPath: '/app/locations/$id'
      preLoaderRoute: typeof AppLocationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses/reports': {
      id: '/app/expenses/reports'
      path: '/expenses/reports'
      fullPath: '/app/expenses/reports'
      preLoaderRoute: typeof AppExpensesReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses/list': {
      id: '/app/expenses/list'
      path: '/expenses/list'
      fullPath: '/app/expenses/list'
      preLoaderRoute: typeof AppExpensesListRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses/categories': {
      id: '/app/expenses/categories'
      path: '/expenses/categories'
      fullPath: '/app/expenses/categories'
      preLoaderRoute: typeof AppExpensesCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contests/new': {
      id: '/app/contests/new'
      path: '/contests/new'
      fullPath: '/app/contests/new'
      preLoaderRoute: typeof AppContestsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contests/$id': {
      id: '/app/contests/$id'
      path: '/contests/$id'
      fullPath: '/app/contests/$id'
      preLoaderRoute: typeof AppContestsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates/new': {
      id: '/app/certificates/new'
      path: '/certificates/new'
      fullPath: '/app/certificates/new'
      preLoaderRoute: typeof AppCertificatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates/$id': {
      id: '/app/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/app/certificates/$id'
      preLoaderRoute: typeof AppCertificatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/new': {
      id: '/app/batches/new'
      path: '/batches/new'
      fullPath: '/app/batches/new'
      preLoaderRoute: typeof AppBatchesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/$id': {
      id: '/app/batches/$id'
      path: '/batches/$id'
      fullPath: '/app/batches/$id'
      preLoaderRoute: typeof AppBatchesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/studios/new': {
      id: '/admin/studios/new'
      path: '/studios/new'
      fullPath: '/admin/studios/new'
      preLoaderRoute: typeof AdminStudiosNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/studios/$id': {
      id: '/admin/studios/$id'
      path: '/studios/$id'
      fullPath: '/admin/studios/$id'
      preLoaderRoute: typeof AdminStudiosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/me/locations/$id_/classes': {
      id: '/me/locations/$id_/classes'
      path: '/locations/$id/classes'
      fullPath: '/me/locations/$id/classes'
      preLoaderRoute: typeof MeLocationsIdClassesRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/checkout/invoice/$invoiceId': {
      id: '/me/checkout/invoice/$invoiceId'
      path: '/checkout/invoice/$invoiceId'
      fullPath: '/me/checkout/invoice/$invoiceId'
      preLoaderRoute: typeof MeCheckoutInvoiceInvoiceIdRouteImport
      parentRoute: typeof MeRoute
    }
    '/app/sessions/$id/attendance': {
      id: '/app/sessions/$id/attendance'
      path: '/sessions/$id/attendance'
      fullPath: '/app/sessions/$id/attendance'
      preLoaderRoute: typeof AppSessionsIdAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations/$id_/edit': {
      id: '/app/locations/$id_/edit'
      path: '/locations/$id/edit'
      fullPath: '/app/locations/$id/edit'
      preLoaderRoute: typeof AppLocationsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations/$id_/classes': {
      id: '/app/locations/$id_/classes'
      path: '/locations/$id/classes'
      fullPath: '/app/locations/$id/classes'
      preLoaderRoute: typeof AppLocationsIdClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/$id_/settings': {
      id: '/app/batches/$id_/settings'
      path: '/batches/$id/settings'
      fullPath: '/app/batches/$id/settings'
      preLoaderRoute: typeof AppBatchesIdSettingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStudiosIdRoute: typeof AdminStudiosIdRoute
  AdminStudiosNewRoute: typeof AdminStudiosNewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStudiosIdRoute: AdminStudiosIdRoute,
  AdminStudiosNewRoute: AdminStudiosNewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppFeedRoute: typeof AppFeedRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRetentionRoute: typeof AppRetentionRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBatchesIdRoute: typeof AppBatchesIdRoute
  AppBatchesNewRoute: typeof AppBatchesNewRoute
  AppCertificatesIdRoute: typeof AppCertificatesIdRoute
  AppCertificatesNewRoute: typeof AppCertificatesNewRoute
  AppContestsIdRoute: typeof AppContestsIdRoute
  AppContestsNewRoute: typeof AppContestsNewRoute
  AppExpensesCategoriesRoute: typeof AppExpensesCategoriesRoute
  AppExpensesListRoute: typeof AppExpensesListRoute
  AppExpensesReportsRoute: typeof AppExpensesReportsRoute
  AppLocationsIdRoute: typeof AppLocationsIdRoute
  AppLocationsNewRoute: typeof AppLocationsNewRoute
  AppMessagesIdRoute: typeof AppMessagesIdRoute
  AppProfileChangeEmailRoute: typeof AppProfileChangeEmailRoute
  AppProfileChangePasswordRoute: typeof AppProfileChangePasswordRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileFollowRequestsRoute: typeof AppProfileFollowRequestsRoute
  AppProfileSecurityRoute: typeof AppProfileSecurityRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsBrandingRoute: typeof AppSettingsBrandingRoute
  AppSettingsPaymentsRoute: typeof AppSettingsPaymentsRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsStylesRoute: typeof AppSettingsStylesRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppStudentsIdRoute: typeof AppStudentsIdRoute
  AppStudentsImportRoute: typeof AppStudentsImportRoute
  AppStudentsNewRoute: typeof AppStudentsNewRoute
  AppSubscriptionsIdRoute: typeof AppSubscriptionsIdRoute
  AppSubscriptionsNewRoute: typeof AppSubscriptionsNewRoute
  AppTrainersNewRoute: typeof AppTrainersNewRoute
  AppBatchesIndexRoute: typeof AppBatchesIndexRoute
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
  AppCertificatesIndexRoute: typeof AppCertificatesIndexRoute
  AppContestsIndexRoute: typeof AppContestsIndexRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppLocationsIndexRoute: typeof AppLocationsIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppSubscriptionsIndexRoute: typeof AppSubscriptionsIndexRoute
  AppTrainersIndexRoute: typeof AppTrainersIndexRoute
  AppBatchesIdSettingsRoute: typeof AppBatchesIdSettingsRoute
  AppLocationsIdClassesRoute: typeof AppLocationsIdClassesRoute
  AppLocationsIdEditRoute: typeof AppLocationsIdEditRoute
  AppSessionsIdAttendanceRoute: typeof AppSessionsIdAttendanceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppFeedRoute: AppFeedRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRetentionRoute: AppRetentionRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBatchesIdRoute: AppBatchesIdRoute,
  AppBatchesNewRoute: AppBatchesNewRoute,
  AppCertificatesIdRoute: AppCertificatesIdRoute,
  AppCertificatesNewRoute: AppCertificatesNewRoute,
  AppContestsIdRoute: AppContestsIdRoute,
  AppContestsNewRoute: AppContestsNewRoute,
  AppExpensesCategoriesRoute: AppExpensesCategoriesRoute,
  AppExpensesListRoute: AppExpensesListRoute,
  AppExpensesReportsRoute: AppExpensesReportsRoute,
  AppLocationsIdRoute: AppLocationsIdRoute,
  AppLocationsNewRoute: AppLocationsNewRoute,
  AppMessagesIdRoute: AppMessagesIdRoute,
  AppProfileChangeEmailRoute: AppProfileChangeEmailRoute,
  AppProfileChangePasswordRoute: AppProfileChangePasswordRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileFollowRequestsRoute: AppProfileFollowRequestsRoute,
  AppProfileSecurityRoute: AppProfileSecurityRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsBrandingRoute: AppSettingsBrandingRoute,
  AppSettingsPaymentsRoute: AppSettingsPaymentsRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsStylesRoute: AppSettingsStylesRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppStudentsIdRoute: AppStudentsIdRoute,
  AppStudentsImportRoute: AppStudentsImportRoute,
  AppStudentsNewRoute: AppStudentsNewRoute,
  AppSubscriptionsIdRoute: AppSubscriptionsIdRoute,
  AppSubscriptionsNewRoute: AppSubscriptionsNewRoute,
  AppTrainersNewRoute: AppTrainersNewRoute,
  AppBatchesIndexRoute: AppBatchesIndexRoute,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
  AppCertificatesIndexRoute: AppCertificatesIndexRoute,
  AppContestsIndexRoute: AppContestsIndexRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppLocationsIndexRoute: AppLocationsIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppSubscriptionsIndexRoute: AppSubscriptionsIndexRoute,
  AppTrainersIndexRoute: AppTrainersIndexRoute,
  AppBatchesIdSettingsRoute: AppBatchesIdSettingsRoute,
  AppLocationsIdClassesRoute: AppLocationsIdClassesRoute,
  AppLocationsIdEditRoute: AppLocationsIdEditRoute,
  AppSessionsIdAttendanceRoute: AppSessionsIdAttendanceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MeRouteChildren {
  MeAttendanceRoute: typeof MeAttendanceRoute
  MeBookRoute: typeof MeBookRoute
  MeBookingsRoute: typeof MeBookingsRoute
  MeCalendarRoute: typeof MeCalendarRoute
  MeCheckInRoute: typeof MeCheckInRoute
  MeContestsRoute: typeof MeContestsRoute
  MeFeedRoute: typeof MeFeedRoute
  MeInvoicesRoute: typeof MeInvoicesRoute
  MeJourneyRoute: typeof MeJourneyRoute
  MeOnboardingRoute: typeof MeOnboardingRoute
  MeProfileRoute: typeof MeProfileRoute
  MeSubscriptionsRoute: typeof MeSubscriptionsRoute
  MeIndexRoute: typeof MeIndexRoute
  MeBatchesIdRoute: typeof MeBatchesIdRoute
  MeCheckoutBookingIdRoute: typeof MeCheckoutBookingIdRoute
  MeLocationsIdRoute: typeof MeLocationsIdRoute
  MeMessagesIdRoute: typeof MeMessagesIdRoute
  MeProfileChangeEmailRoute: typeof MeProfileChangeEmailRoute
  MeProfileChangePasswordRoute: typeof MeProfileChangePasswordRoute
  MeProfileEditRoute: typeof MeProfileEditRoute
  MeProfileFollowRequestsRoute: typeof MeProfileFollowRequestsRoute
  MeProfileSecurityRoute: typeof MeProfileSecurityRoute
  MeLocationsIndexRoute: typeof MeLocationsIndexRoute
  MeMessagesIndexRoute: typeof MeMessagesIndexRoute
  MeTrainersIndexRoute: typeof MeTrainersIndexRoute
  MeCheckoutInvoiceInvoiceIdRoute: typeof MeCheckoutInvoiceInvoiceIdRoute
  MeLocationsIdClassesRoute: typeof MeLocationsIdClassesRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeAttendanceRoute: MeAttendanceRoute,
  MeBookRoute: MeBookRoute,
  MeBookingsRoute: MeBookingsRoute,
  MeCalendarRoute: MeCalendarRoute,
  MeCheckInRoute: MeCheckInRoute,
  MeContestsRoute: MeContestsRoute,
  MeFeedRoute: MeFeedRoute,
  MeInvoicesRoute: MeInvoicesRoute,
  MeJourneyRoute: MeJourneyRoute,
  MeOnboardingRoute: MeOnboardingRoute,
  MeProfileRoute: MeProfileRoute,
  MeSubscriptionsRoute: MeSubscriptionsRoute,
  MeIndexRoute: MeIndexRoute,
  MeBatchesIdRoute: MeBatchesIdRoute,
  MeCheckoutBookingIdRoute: MeCheckoutBookingIdRoute,
  MeLocationsIdRoute: MeLocationsIdRoute,
  MeMessagesIdRoute: MeMessagesIdRoute,
  MeProfileChangeEmailRoute: MeProfileChangeEmailRoute,
  MeProfileChangePasswordRoute: MeProfileChangePasswordRoute,
  MeProfileEditRoute: MeProfileEditRoute,
  MeProfileFollowRequestsRoute: MeProfileFollowRequestsRoute,
  MeProfileSecurityRoute: MeProfileSecurityRoute,
  MeLocationsIndexRoute: MeLocationsIndexRoute,
  MeMessagesIndexRoute: MeMessagesIndexRoute,
  MeTrainersIndexRoute: MeTrainersIndexRoute,
  MeCheckoutInvoiceInvoiceIdRoute: MeCheckoutInvoiceInvoiceIdRoute,
  MeLocationsIdClassesRoute: MeLocationsIdClassesRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRouteWithChildren,
  RegisterRoute: RegisterRoute,
  PostsIdRoute: PostsIdRoute,
  StudioStudioIdRoute: StudioStudioIdRoute,
  TrainersIdRoute: TrainersIdRoute,
  UsersIdRoute: UsersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
