/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeIndexRouteImport } from './routes/me/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as TrainersIdRouteImport } from './routes/trainers.$id'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as MeSubscriptionsRouteImport } from './routes/me/subscriptions'
import { Route as MeProfileRouteImport } from './routes/me/profile'
import { Route as MeOnboardingRouteImport } from './routes/me/onboarding'
import { Route as MeInvoicesRouteImport } from './routes/me/invoices'
import { Route as MeFeedRouteImport } from './routes/me/feed'
import { Route as MeContestsRouteImport } from './routes/me/contests'
import { Route as MeCheckInRouteImport } from './routes/me/check-in'
import { Route as MeCalendarRouteImport } from './routes/me/calendar'
import { Route as MeBookingsRouteImport } from './routes/me/bookings'
import { Route as MeBookRouteImport } from './routes/me/book'
import { Route as MeAttendanceRouteImport } from './routes/me/attendance'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppRetentionRouteImport } from './routes/app/retention'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPaymentsRouteImport } from './routes/app/payments'
import { Route as AppInvoicesRouteImport } from './routes/app/invoices'
import { Route as AppFeedRouteImport } from './routes/app/feed'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as MeTrainersIndexRouteImport } from './routes/me/trainers/index'
import { Route as MeMessagesIndexRouteImport } from './routes/me/messages/index'
import { Route as MeLocationsIndexRouteImport } from './routes/me/locations/index'
import { Route as AppTrainersIndexRouteImport } from './routes/app/trainers/index'
import { Route as AppSubscriptionsIndexRouteImport } from './routes/app/subscriptions/index'
import { Route as AppStudentsIndexRouteImport } from './routes/app/students/index'
import { Route as AppMessagesIndexRouteImport } from './routes/app/messages/index'
import { Route as AppLocationsIndexRouteImport } from './routes/app/locations/index'
import { Route as AppContestsIndexRouteImport } from './routes/app/contests/index'
import { Route as AppCertificatesIndexRouteImport } from './routes/app/certificates/index'
import { Route as AppBookingsIndexRouteImport } from './routes/app/bookings/index'
import { Route as AppBatchesIndexRouteImport } from './routes/app/batches/index'
import { Route as MeProfileFollowRequestsRouteImport } from './routes/me/profile_.follow-requests'
import { Route as MeProfileEditRouteImport } from './routes/me/profile_.edit'
import { Route as MeMessagesIdRouteImport } from './routes/me/messages/$id'
import { Route as MeLocationsIdRouteImport } from './routes/me/locations/$id'
import { Route as MeBatchesIdRouteImport } from './routes/me/batches/$id'
import { Route as AppTrainersNewRouteImport } from './routes/app/trainers/new'
import { Route as AppSubscriptionsNewRouteImport } from './routes/app/subscriptions/new'
import { Route as AppSubscriptionsIdRouteImport } from './routes/app/subscriptions/$id'
import { Route as AppStudentsNewRouteImport } from './routes/app/students/new'
import { Route as AppStudentsImportRouteImport } from './routes/app/students/import'
import { Route as AppStudentsIdRouteImport } from './routes/app/students/$id'
import { Route as AppProfileFollowRequestsRouteImport } from './routes/app/profile_.follow-requests'
import { Route as AppProfileEditRouteImport } from './routes/app/profile_.edit'
import { Route as AppMessagesIdRouteImport } from './routes/app/messages/$id'
import { Route as AppLocationsIdRouteImport } from './routes/app/locations/$id'
import { Route as AppContestsNewRouteImport } from './routes/app/contests/new'
import { Route as AppContestsIdRouteImport } from './routes/app/contests/$id'
import { Route as AppCertificatesNewRouteImport } from './routes/app/certificates/new'
import { Route as AppCertificatesIdRouteImport } from './routes/app/certificates/$id'
import { Route as AppBookingsNewRouteImport } from './routes/app/bookings/new'
import { Route as AppBatchesNewRouteImport } from './routes/app/batches/new'
import { Route as AppBatchesIdRouteImport } from './routes/app/batches/$id'
import { Route as MeLocationsIdClassesRouteImport } from './routes/me/locations/$id_.classes'
import { Route as AppSessionsIdAttendanceRouteImport } from './routes/app/sessions.$id.attendance'
import { Route as AppLocationsIdClassesRouteImport } from './routes/app/locations/$id_.classes'
import { Route as AppLocationsIdEditRouteImport } from './routes/app/locations/$id.edit'

const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeIndexRoute = MeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersIdRoute = TrainersIdRouteImport.update({
  id: '/trainers/$id',
  path: '/trainers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeSubscriptionsRoute = MeSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => MeRoute,
} as any)
const MeProfileRoute = MeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MeRoute,
} as any)
const MeOnboardingRoute = MeOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => MeRoute,
} as any)
const MeInvoicesRoute = MeInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => MeRoute,
} as any)
const MeFeedRoute = MeFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => MeRoute,
} as any)
const MeContestsRoute = MeContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => MeRoute,
} as any)
const MeCheckInRoute = MeCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => MeRoute,
} as any)
const MeCalendarRoute = MeCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => MeRoute,
} as any)
const MeBookingsRoute = MeBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => MeRoute,
} as any)
const MeBookRoute = MeBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => MeRoute,
} as any)
const MeAttendanceRoute = MeAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => MeRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRetentionRoute = AppRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const MeTrainersIndexRoute = MeTrainersIndexRouteImport.update({
  id: '/trainers/',
  path: '/trainers/',
  getParentRoute: () => MeRoute,
} as any)
const MeMessagesIndexRoute = MeMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => MeRoute,
} as any)
const MeLocationsIndexRoute = MeLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => MeRoute,
} as any)
const AppTrainersIndexRoute = AppTrainersIndexRouteImport.update({
  id: '/trainers/',
  path: '/trainers/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsIndexRoute = AppSubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIndexRoute = AppStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIndexRoute = AppLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AppRoute,
} as any)
const AppContestsIndexRoute = AppContestsIndexRouteImport.update({
  id: '/contests/',
  path: '/contests/',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesIndexRoute = AppCertificatesIndexRouteImport.update({
  id: '/certificates/',
  path: '/certificates/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsIndexRoute = AppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIndexRoute = AppBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => AppRoute,
} as any)
const MeProfileFollowRequestsRoute = MeProfileFollowRequestsRouteImport.update({
  id: '/profile_/follow-requests',
  path: '/profile/follow-requests',
  getParentRoute: () => MeRoute,
} as any)
const MeProfileEditRoute = MeProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => MeRoute,
} as any)
const MeMessagesIdRoute = MeMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => MeRoute,
} as any)
const MeLocationsIdRoute = MeLocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => MeRoute,
} as any)
const MeBatchesIdRoute = MeBatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => MeRoute,
} as any)
const AppTrainersNewRoute = AppTrainersNewRouteImport.update({
  id: '/trainers/new',
  path: '/trainers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsNewRoute = AppSubscriptionsNewRouteImport.update({
  id: '/subscriptions/new',
  path: '/subscriptions/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsIdRoute = AppSubscriptionsIdRouteImport.update({
  id: '/subscriptions/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsNewRoute = AppStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsImportRoute = AppStudentsImportRouteImport.update({
  id: '/students/import',
  path: '/students/import',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsIdRoute = AppStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileFollowRequestsRoute =
  AppProfileFollowRequestsRouteImport.update({
    id: '/profile_/follow-requests',
    path: '/profile/follow-requests',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIdRoute = AppMessagesIdRouteImport.update({
  id: '/messages/$id',
  path: '/messages/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIdRoute = AppLocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContestsNewRoute = AppContestsNewRouteImport.update({
  id: '/contests/new',
  path: '/contests/new',
  getParentRoute: () => AppRoute,
} as any)
const AppContestsIdRoute = AppContestsIdRouteImport.update({
  id: '/contests/$id',
  path: '/contests/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesNewRoute = AppCertificatesNewRouteImport.update({
  id: '/certificates/new',
  path: '/certificates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesIdRoute = AppCertificatesIdRouteImport.update({
  id: '/certificates/$id',
  path: '/certificates/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsNewRoute = AppBookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesNewRoute = AppBatchesNewRouteImport.update({
  id: '/batches/new',
  path: '/batches/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBatchesIdRoute = AppBatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => AppRoute,
} as any)
const MeLocationsIdClassesRoute = MeLocationsIdClassesRouteImport.update({
  id: '/locations/$id_/classes',
  path: '/locations/$id/classes',
  getParentRoute: () => MeRoute,
} as any)
const AppSessionsIdAttendanceRoute = AppSessionsIdAttendanceRouteImport.update({
  id: '/sessions/$id/attendance',
  path: '/sessions/$id/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIdClassesRoute = AppLocationsIdClassesRouteImport.update({
  id: '/locations/$id_/classes',
  path: '/locations/$id/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsIdEditRoute = AppLocationsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppLocationsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/register': typeof RegisterRoute
  '/studio': typeof StudioRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/feed': typeof AppFeedRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/retention': typeof AppRetentionRoute
  '/app/settings': typeof AppSettingsRoute
  '/me/attendance': typeof MeAttendanceRoute
  '/me/book': typeof MeBookRoute
  '/me/bookings': typeof MeBookingsRoute
  '/me/calendar': typeof MeCalendarRoute
  '/me/check-in': typeof MeCheckInRoute
  '/me/contests': typeof MeContestsRoute
  '/me/feed': typeof MeFeedRoute
  '/me/invoices': typeof MeInvoicesRoute
  '/me/onboarding': typeof MeOnboardingRoute
  '/me/profile': typeof MeProfileRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/posts/$id': typeof PostsIdRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/users/$id': typeof UsersIdRoute
  '/app/': typeof AppIndexRoute
  '/me/': typeof MeIndexRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/batches/new': typeof AppBatchesNewRoute
  '/app/bookings/new': typeof AppBookingsNewRoute
  '/app/certificates/$id': typeof AppCertificatesIdRoute
  '/app/certificates/new': typeof AppCertificatesNewRoute
  '/app/contests/$id': typeof AppContestsIdRoute
  '/app/contests/new': typeof AppContestsNewRoute
  '/app/locations/$id': typeof AppLocationsIdRouteWithChildren
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/follow-requests': typeof AppProfileFollowRequestsRoute
  '/app/students/$id': typeof AppStudentsIdRoute
  '/app/students/import': typeof AppStudentsImportRoute
  '/app/students/new': typeof AppStudentsNewRoute
  '/app/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/app/subscriptions/new': typeof AppSubscriptionsNewRoute
  '/app/trainers/new': typeof AppTrainersNewRoute
  '/me/batches/$id': typeof MeBatchesIdRoute
  '/me/locations/$id': typeof MeLocationsIdRoute
  '/me/messages/$id': typeof MeMessagesIdRoute
  '/me/profile/edit': typeof MeProfileEditRoute
  '/me/profile/follow-requests': typeof MeProfileFollowRequestsRoute
  '/app/batches/': typeof AppBatchesIndexRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
  '/app/certificates/': typeof AppCertificatesIndexRoute
  '/app/contests/': typeof AppContestsIndexRoute
  '/app/locations/': typeof AppLocationsIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
  '/app/subscriptions/': typeof AppSubscriptionsIndexRoute
  '/app/trainers/': typeof AppTrainersIndexRoute
  '/me/locations/': typeof MeLocationsIndexRoute
  '/me/messages/': typeof MeMessagesIndexRoute
  '/me/trainers/': typeof MeTrainersIndexRoute
  '/app/locations/$id/edit': typeof AppLocationsIdEditRoute
  '/app/locations/$id/classes': typeof AppLocationsIdClassesRoute
  '/app/sessions/$id/attendance': typeof AppSessionsIdAttendanceRoute
  '/me/locations/$id/classes': typeof MeLocationsIdClassesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/studio': typeof StudioRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/feed': typeof AppFeedRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/retention': typeof AppRetentionRoute
  '/app/settings': typeof AppSettingsRoute
  '/me/attendance': typeof MeAttendanceRoute
  '/me/book': typeof MeBookRoute
  '/me/bookings': typeof MeBookingsRoute
  '/me/calendar': typeof MeCalendarRoute
  '/me/check-in': typeof MeCheckInRoute
  '/me/contests': typeof MeContestsRoute
  '/me/feed': typeof MeFeedRoute
  '/me/invoices': typeof MeInvoicesRoute
  '/me/onboarding': typeof MeOnboardingRoute
  '/me/profile': typeof MeProfileRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/posts/$id': typeof PostsIdRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/users/$id': typeof UsersIdRoute
  '/app': typeof AppIndexRoute
  '/me': typeof MeIndexRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/batches/new': typeof AppBatchesNewRoute
  '/app/bookings/new': typeof AppBookingsNewRoute
  '/app/certificates/$id': typeof AppCertificatesIdRoute
  '/app/certificates/new': typeof AppCertificatesNewRoute
  '/app/contests/$id': typeof AppContestsIdRoute
  '/app/contests/new': typeof AppContestsNewRoute
  '/app/locations/$id': typeof AppLocationsIdRouteWithChildren
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/profile/follow-requests': typeof AppProfileFollowRequestsRoute
  '/app/students/$id': typeof AppStudentsIdRoute
  '/app/students/import': typeof AppStudentsImportRoute
  '/app/students/new': typeof AppStudentsNewRoute
  '/app/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/app/subscriptions/new': typeof AppSubscriptionsNewRoute
  '/app/trainers/new': typeof AppTrainersNewRoute
  '/me/batches/$id': typeof MeBatchesIdRoute
  '/me/locations/$id': typeof MeLocationsIdRoute
  '/me/messages/$id': typeof MeMessagesIdRoute
  '/me/profile/edit': typeof MeProfileEditRoute
  '/me/profile/follow-requests': typeof MeProfileFollowRequestsRoute
  '/app/batches': typeof AppBatchesIndexRoute
  '/app/bookings': typeof AppBookingsIndexRoute
  '/app/certificates': typeof AppCertificatesIndexRoute
  '/app/contests': typeof AppContestsIndexRoute
  '/app/locations': typeof AppLocationsIndexRoute
  '/app/messages': typeof AppMessagesIndexRoute
  '/app/students': typeof AppStudentsIndexRoute
  '/app/subscriptions': typeof AppSubscriptionsIndexRoute
  '/app/trainers': typeof AppTrainersIndexRoute
  '/me/locations': typeof MeLocationsIndexRoute
  '/me/messages': typeof MeMessagesIndexRoute
  '/me/trainers': typeof MeTrainersIndexRoute
  '/app/locations/$id/edit': typeof AppLocationsIdEditRoute
  '/app/locations/$id/classes': typeof AppLocationsIdClassesRoute
  '/app/sessions/$id/attendance': typeof AppSessionsIdAttendanceRoute
  '/me/locations/$id/classes': typeof MeLocationsIdClassesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/me': typeof MeRouteWithChildren
  '/register': typeof RegisterRoute
  '/studio': typeof StudioRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/feed': typeof AppFeedRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/retention': typeof AppRetentionRoute
  '/app/settings': typeof AppSettingsRoute
  '/me/attendance': typeof MeAttendanceRoute
  '/me/book': typeof MeBookRoute
  '/me/bookings': typeof MeBookingsRoute
  '/me/calendar': typeof MeCalendarRoute
  '/me/check-in': typeof MeCheckInRoute
  '/me/contests': typeof MeContestsRoute
  '/me/feed': typeof MeFeedRoute
  '/me/invoices': typeof MeInvoicesRoute
  '/me/onboarding': typeof MeOnboardingRoute
  '/me/profile': typeof MeProfileRoute
  '/me/subscriptions': typeof MeSubscriptionsRoute
  '/posts/$id': typeof PostsIdRoute
  '/trainers/$id': typeof TrainersIdRoute
  '/users/$id': typeof UsersIdRoute
  '/app/': typeof AppIndexRoute
  '/me/': typeof MeIndexRoute
  '/app/batches/$id': typeof AppBatchesIdRoute
  '/app/batches/new': typeof AppBatchesNewRoute
  '/app/bookings/new': typeof AppBookingsNewRoute
  '/app/certificates/$id': typeof AppCertificatesIdRoute
  '/app/certificates/new': typeof AppCertificatesNewRoute
  '/app/contests/$id': typeof AppContestsIdRoute
  '/app/contests/new': typeof AppContestsNewRoute
  '/app/locations/$id': typeof AppLocationsIdRouteWithChildren
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/profile_/edit': typeof AppProfileEditRoute
  '/app/profile_/follow-requests': typeof AppProfileFollowRequestsRoute
  '/app/students/$id': typeof AppStudentsIdRoute
  '/app/students/import': typeof AppStudentsImportRoute
  '/app/students/new': typeof AppStudentsNewRoute
  '/app/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/app/subscriptions/new': typeof AppSubscriptionsNewRoute
  '/app/trainers/new': typeof AppTrainersNewRoute
  '/me/batches/$id': typeof MeBatchesIdRoute
  '/me/locations/$id': typeof MeLocationsIdRoute
  '/me/messages/$id': typeof MeMessagesIdRoute
  '/me/profile_/edit': typeof MeProfileEditRoute
  '/me/profile_/follow-requests': typeof MeProfileFollowRequestsRoute
  '/app/batches/': typeof AppBatchesIndexRoute
  '/app/bookings/': typeof AppBookingsIndexRoute
  '/app/certificates/': typeof AppCertificatesIndexRoute
  '/app/contests/': typeof AppContestsIndexRoute
  '/app/locations/': typeof AppLocationsIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/students/': typeof AppStudentsIndexRoute
  '/app/subscriptions/': typeof AppSubscriptionsIndexRoute
  '/app/trainers/': typeof AppTrainersIndexRoute
  '/me/locations/': typeof MeLocationsIndexRoute
  '/me/messages/': typeof MeMessagesIndexRoute
  '/me/trainers/': typeof MeTrainersIndexRoute
  '/app/locations/$id/edit': typeof AppLocationsIdEditRoute
  '/app/locations/$id_/classes': typeof AppLocationsIdClassesRoute
  '/app/sessions/$id/attendance': typeof AppSessionsIdAttendanceRoute
  '/me/locations/$id_/classes': typeof MeLocationsIdClassesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/me'
    | '/register'
    | '/studio'
    | '/app/calendar'
    | '/app/feed'
    | '/app/invoices'
    | '/app/payments'
    | '/app/profile'
    | '/app/retention'
    | '/app/settings'
    | '/me/attendance'
    | '/me/book'
    | '/me/bookings'
    | '/me/calendar'
    | '/me/check-in'
    | '/me/contests'
    | '/me/feed'
    | '/me/invoices'
    | '/me/onboarding'
    | '/me/profile'
    | '/me/subscriptions'
    | '/posts/$id'
    | '/trainers/$id'
    | '/users/$id'
    | '/app/'
    | '/me/'
    | '/app/batches/$id'
    | '/app/batches/new'
    | '/app/bookings/new'
    | '/app/certificates/$id'
    | '/app/certificates/new'
    | '/app/contests/$id'
    | '/app/contests/new'
    | '/app/locations/$id'
    | '/app/messages/$id'
    | '/app/profile/edit'
    | '/app/profile/follow-requests'
    | '/app/students/$id'
    | '/app/students/import'
    | '/app/students/new'
    | '/app/subscriptions/$id'
    | '/app/subscriptions/new'
    | '/app/trainers/new'
    | '/me/batches/$id'
    | '/me/locations/$id'
    | '/me/messages/$id'
    | '/me/profile/edit'
    | '/me/profile/follow-requests'
    | '/app/batches/'
    | '/app/bookings/'
    | '/app/certificates/'
    | '/app/contests/'
    | '/app/locations/'
    | '/app/messages/'
    | '/app/students/'
    | '/app/subscriptions/'
    | '/app/trainers/'
    | '/me/locations/'
    | '/me/messages/'
    | '/me/trainers/'
    | '/app/locations/$id/edit'
    | '/app/locations/$id/classes'
    | '/app/sessions/$id/attendance'
    | '/me/locations/$id/classes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/studio'
    | '/app/calendar'
    | '/app/feed'
    | '/app/invoices'
    | '/app/payments'
    | '/app/profile'
    | '/app/retention'
    | '/app/settings'
    | '/me/attendance'
    | '/me/book'
    | '/me/bookings'
    | '/me/calendar'
    | '/me/check-in'
    | '/me/contests'
    | '/me/feed'
    | '/me/invoices'
    | '/me/onboarding'
    | '/me/profile'
    | '/me/subscriptions'
    | '/posts/$id'
    | '/trainers/$id'
    | '/users/$id'
    | '/app'
    | '/me'
    | '/app/batches/$id'
    | '/app/batches/new'
    | '/app/bookings/new'
    | '/app/certificates/$id'
    | '/app/certificates/new'
    | '/app/contests/$id'
    | '/app/contests/new'
    | '/app/locations/$id'
    | '/app/messages/$id'
    | '/app/profile/edit'
    | '/app/profile/follow-requests'
    | '/app/students/$id'
    | '/app/students/import'
    | '/app/students/new'
    | '/app/subscriptions/$id'
    | '/app/subscriptions/new'
    | '/app/trainers/new'
    | '/me/batches/$id'
    | '/me/locations/$id'
    | '/me/messages/$id'
    | '/me/profile/edit'
    | '/me/profile/follow-requests'
    | '/app/batches'
    | '/app/bookings'
    | '/app/certificates'
    | '/app/contests'
    | '/app/locations'
    | '/app/messages'
    | '/app/students'
    | '/app/subscriptions'
    | '/app/trainers'
    | '/me/locations'
    | '/me/messages'
    | '/me/trainers'
    | '/app/locations/$id/edit'
    | '/app/locations/$id/classes'
    | '/app/sessions/$id/attendance'
    | '/me/locations/$id/classes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/me'
    | '/register'
    | '/studio'
    | '/app/calendar'
    | '/app/feed'
    | '/app/invoices'
    | '/app/payments'
    | '/app/profile'
    | '/app/retention'
    | '/app/settings'
    | '/me/attendance'
    | '/me/book'
    | '/me/bookings'
    | '/me/calendar'
    | '/me/check-in'
    | '/me/contests'
    | '/me/feed'
    | '/me/invoices'
    | '/me/onboarding'
    | '/me/profile'
    | '/me/subscriptions'
    | '/posts/$id'
    | '/trainers/$id'
    | '/users/$id'
    | '/app/'
    | '/me/'
    | '/app/batches/$id'
    | '/app/batches/new'
    | '/app/bookings/new'
    | '/app/certificates/$id'
    | '/app/certificates/new'
    | '/app/contests/$id'
    | '/app/contests/new'
    | '/app/locations/$id'
    | '/app/messages/$id'
    | '/app/profile_/edit'
    | '/app/profile_/follow-requests'
    | '/app/students/$id'
    | '/app/students/import'
    | '/app/students/new'
    | '/app/subscriptions/$id'
    | '/app/subscriptions/new'
    | '/app/trainers/new'
    | '/me/batches/$id'
    | '/me/locations/$id'
    | '/me/messages/$id'
    | '/me/profile_/edit'
    | '/me/profile_/follow-requests'
    | '/app/batches/'
    | '/app/bookings/'
    | '/app/certificates/'
    | '/app/contests/'
    | '/app/locations/'
    | '/app/messages/'
    | '/app/students/'
    | '/app/subscriptions/'
    | '/app/trainers/'
    | '/me/locations/'
    | '/me/messages/'
    | '/me/trainers/'
    | '/app/locations/$id/edit'
    | '/app/locations/$id_/classes'
    | '/app/sessions/$id/attendance'
    | '/me/locations/$id_/classes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  StudioRoute: typeof StudioRoute
  PostsIdRoute: typeof PostsIdRoute
  TrainersIdRoute: typeof TrainersIdRoute
  UsersIdRoute: typeof UsersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/': {
      id: '/me/'
      path: '/'
      fullPath: '/me/'
      preLoaderRoute: typeof MeIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers/$id': {
      id: '/trainers/$id'
      path: '/trainers/$id'
      fullPath: '/trainers/$id'
      preLoaderRoute: typeof TrainersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/subscriptions': {
      id: '/me/subscriptions'
      path: '/subscriptions'
      fullPath: '/me/subscriptions'
      preLoaderRoute: typeof MeSubscriptionsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/profile': {
      id: '/me/profile'
      path: '/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof MeProfileRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/onboarding': {
      id: '/me/onboarding'
      path: '/onboarding'
      fullPath: '/me/onboarding'
      preLoaderRoute: typeof MeOnboardingRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/invoices': {
      id: '/me/invoices'
      path: '/invoices'
      fullPath: '/me/invoices'
      preLoaderRoute: typeof MeInvoicesRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/feed': {
      id: '/me/feed'
      path: '/feed'
      fullPath: '/me/feed'
      preLoaderRoute: typeof MeFeedRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/contests': {
      id: '/me/contests'
      path: '/contests'
      fullPath: '/me/contests'
      preLoaderRoute: typeof MeContestsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/check-in': {
      id: '/me/check-in'
      path: '/check-in'
      fullPath: '/me/check-in'
      preLoaderRoute: typeof MeCheckInRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/calendar': {
      id: '/me/calendar'
      path: '/calendar'
      fullPath: '/me/calendar'
      preLoaderRoute: typeof MeCalendarRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/bookings': {
      id: '/me/bookings'
      path: '/bookings'
      fullPath: '/me/bookings'
      preLoaderRoute: typeof MeBookingsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/book': {
      id: '/me/book'
      path: '/book'
      fullPath: '/me/book'
      preLoaderRoute: typeof MeBookRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/attendance': {
      id: '/me/attendance'
      path: '/attendance'
      fullPath: '/me/attendance'
      preLoaderRoute: typeof MeAttendanceRouteImport
      parentRoute: typeof MeRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/retention': {
      id: '/app/retention'
      path: '/retention'
      fullPath: '/app/retention'
      preLoaderRoute: typeof AppRetentionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/me/trainers/': {
      id: '/me/trainers/'
      path: '/trainers'
      fullPath: '/me/trainers/'
      preLoaderRoute: typeof MeTrainersIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/messages/': {
      id: '/me/messages/'
      path: '/messages'
      fullPath: '/me/messages/'
      preLoaderRoute: typeof MeMessagesIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/locations/': {
      id: '/me/locations/'
      path: '/locations'
      fullPath: '/me/locations/'
      preLoaderRoute: typeof MeLocationsIndexRouteImport
      parentRoute: typeof MeRoute
    }
    '/app/trainers/': {
      id: '/app/trainers/'
      path: '/trainers'
      fullPath: '/app/trainers/'
      preLoaderRoute: typeof AppTrainersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions/': {
      id: '/app/subscriptions/'
      path: '/subscriptions'
      fullPath: '/app/subscriptions/'
      preLoaderRoute: typeof AppSubscriptionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/': {
      id: '/app/students/'
      path: '/students'
      fullPath: '/app/students/'
      preLoaderRoute: typeof AppStudentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/': {
      id: '/app/messages/'
      path: '/messages'
      fullPath: '/app/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations/': {
      id: '/app/locations/'
      path: '/locations'
      fullPath: '/app/locations/'
      preLoaderRoute: typeof AppLocationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contests/': {
      id: '/app/contests/'
      path: '/contests'
      fullPath: '/app/contests/'
      preLoaderRoute: typeof AppContestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates/': {
      id: '/app/certificates/'
      path: '/certificates'
      fullPath: '/app/certificates/'
      preLoaderRoute: typeof AppCertificatesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings/': {
      id: '/app/bookings/'
      path: '/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AppBookingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/': {
      id: '/app/batches/'
      path: '/batches'
      fullPath: '/app/batches/'
      preLoaderRoute: typeof AppBatchesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/me/profile_/follow-requests': {
      id: '/me/profile_/follow-requests'
      path: '/profile/follow-requests'
      fullPath: '/me/profile/follow-requests'
      preLoaderRoute: typeof MeProfileFollowRequestsRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/profile_/edit': {
      id: '/me/profile_/edit'
      path: '/profile/edit'
      fullPath: '/me/profile/edit'
      preLoaderRoute: typeof MeProfileEditRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/messages/$id': {
      id: '/me/messages/$id'
      path: '/messages/$id'
      fullPath: '/me/messages/$id'
      preLoaderRoute: typeof MeMessagesIdRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/locations/$id': {
      id: '/me/locations/$id'
      path: '/locations/$id'
      fullPath: '/me/locations/$id'
      preLoaderRoute: typeof MeLocationsIdRouteImport
      parentRoute: typeof MeRoute
    }
    '/me/batches/$id': {
      id: '/me/batches/$id'
      path: '/batches/$id'
      fullPath: '/me/batches/$id'
      preLoaderRoute: typeof MeBatchesIdRouteImport
      parentRoute: typeof MeRoute
    }
    '/app/trainers/new': {
      id: '/app/trainers/new'
      path: '/trainers/new'
      fullPath: '/app/trainers/new'
      preLoaderRoute: typeof AppTrainersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions/new': {
      id: '/app/subscriptions/new'
      path: '/subscriptions/new'
      fullPath: '/app/subscriptions/new'
      preLoaderRoute: typeof AppSubscriptionsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions/$id': {
      id: '/app/subscriptions/$id'
      path: '/subscriptions/$id'
      fullPath: '/app/subscriptions/$id'
      preLoaderRoute: typeof AppSubscriptionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/new': {
      id: '/app/students/new'
      path: '/students/new'
      fullPath: '/app/students/new'
      preLoaderRoute: typeof AppStudentsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/import': {
      id: '/app/students/import'
      path: '/students/import'
      fullPath: '/app/students/import'
      preLoaderRoute: typeof AppStudentsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students/$id': {
      id: '/app/students/$id'
      path: '/students/$id'
      fullPath: '/app/students/$id'
      preLoaderRoute: typeof AppStudentsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile_/follow-requests': {
      id: '/app/profile_/follow-requests'
      path: '/profile/follow-requests'
      fullPath: '/app/profile/follow-requests'
      preLoaderRoute: typeof AppProfileFollowRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile_/edit': {
      id: '/app/profile_/edit'
      path: '/profile/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/$id': {
      id: '/app/messages/$id'
      path: '/messages/$id'
      fullPath: '/app/messages/$id'
      preLoaderRoute: typeof AppMessagesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations/$id': {
      id: '/app/locations/$id'
      path: '/locations/$id'
      fullPath: '/app/locations/$id'
      preLoaderRoute: typeof AppLocationsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contests/new': {
      id: '/app/contests/new'
      path: '/contests/new'
      fullPath: '/app/contests/new'
      preLoaderRoute: typeof AppContestsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contests/$id': {
      id: '/app/contests/$id'
      path: '/contests/$id'
      fullPath: '/app/contests/$id'
      preLoaderRoute: typeof AppContestsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates/new': {
      id: '/app/certificates/new'
      path: '/certificates/new'
      fullPath: '/app/certificates/new'
      preLoaderRoute: typeof AppCertificatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/certificates/$id': {
      id: '/app/certificates/$id'
      path: '/certificates/$id'
      fullPath: '/app/certificates/$id'
      preLoaderRoute: typeof AppCertificatesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings/new': {
      id: '/app/bookings/new'
      path: '/bookings/new'
      fullPath: '/app/bookings/new'
      preLoaderRoute: typeof AppBookingsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/new': {
      id: '/app/batches/new'
      path: '/batches/new'
      fullPath: '/app/batches/new'
      preLoaderRoute: typeof AppBatchesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/batches/$id': {
      id: '/app/batches/$id'
      path: '/batches/$id'
      fullPath: '/app/batches/$id'
      preLoaderRoute: typeof AppBatchesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/me/locations/$id_/classes': {
      id: '/me/locations/$id_/classes'
      path: '/locations/$id/classes'
      fullPath: '/me/locations/$id/classes'
      preLoaderRoute: typeof MeLocationsIdClassesRouteImport
      parentRoute: typeof MeRoute
    }
    '/app/sessions/$id/attendance': {
      id: '/app/sessions/$id/attendance'
      path: '/sessions/$id/attendance'
      fullPath: '/app/sessions/$id/attendance'
      preLoaderRoute: typeof AppSessionsIdAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations/$id_/classes': {
      id: '/app/locations/$id_/classes'
      path: '/locations/$id/classes'
      fullPath: '/app/locations/$id/classes'
      preLoaderRoute: typeof AppLocationsIdClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations/$id/edit': {
      id: '/app/locations/$id/edit'
      path: '/edit'
      fullPath: '/app/locations/$id/edit'
      preLoaderRoute: typeof AppLocationsIdEditRouteImport
      parentRoute: typeof AppLocationsIdRoute
    }
  }
}

interface AppLocationsIdRouteChildren {
  AppLocationsIdEditRoute: typeof AppLocationsIdEditRoute
}

const AppLocationsIdRouteChildren: AppLocationsIdRouteChildren = {
  AppLocationsIdEditRoute: AppLocationsIdEditRoute,
}

const AppLocationsIdRouteWithChildren = AppLocationsIdRoute._addFileChildren(
  AppLocationsIdRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppFeedRoute: typeof AppFeedRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRetentionRoute: typeof AppRetentionRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBatchesIdRoute: typeof AppBatchesIdRoute
  AppBatchesNewRoute: typeof AppBatchesNewRoute
  AppBookingsNewRoute: typeof AppBookingsNewRoute
  AppCertificatesIdRoute: typeof AppCertificatesIdRoute
  AppCertificatesNewRoute: typeof AppCertificatesNewRoute
  AppContestsIdRoute: typeof AppContestsIdRoute
  AppContestsNewRoute: typeof AppContestsNewRoute
  AppLocationsIdRoute: typeof AppLocationsIdRouteWithChildren
  AppMessagesIdRoute: typeof AppMessagesIdRoute
  AppProfileEditRoute: typeof AppProfileEditRoute
  AppProfileFollowRequestsRoute: typeof AppProfileFollowRequestsRoute
  AppStudentsIdRoute: typeof AppStudentsIdRoute
  AppStudentsImportRoute: typeof AppStudentsImportRoute
  AppStudentsNewRoute: typeof AppStudentsNewRoute
  AppSubscriptionsIdRoute: typeof AppSubscriptionsIdRoute
  AppSubscriptionsNewRoute: typeof AppSubscriptionsNewRoute
  AppTrainersNewRoute: typeof AppTrainersNewRoute
  AppBatchesIndexRoute: typeof AppBatchesIndexRoute
  AppBookingsIndexRoute: typeof AppBookingsIndexRoute
  AppCertificatesIndexRoute: typeof AppCertificatesIndexRoute
  AppContestsIndexRoute: typeof AppContestsIndexRoute
  AppLocationsIndexRoute: typeof AppLocationsIndexRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
  AppStudentsIndexRoute: typeof AppStudentsIndexRoute
  AppSubscriptionsIndexRoute: typeof AppSubscriptionsIndexRoute
  AppTrainersIndexRoute: typeof AppTrainersIndexRoute
  AppLocationsIdClassesRoute: typeof AppLocationsIdClassesRoute
  AppSessionsIdAttendanceRoute: typeof AppSessionsIdAttendanceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppFeedRoute: AppFeedRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRetentionRoute: AppRetentionRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBatchesIdRoute: AppBatchesIdRoute,
  AppBatchesNewRoute: AppBatchesNewRoute,
  AppBookingsNewRoute: AppBookingsNewRoute,
  AppCertificatesIdRoute: AppCertificatesIdRoute,
  AppCertificatesNewRoute: AppCertificatesNewRoute,
  AppContestsIdRoute: AppContestsIdRoute,
  AppContestsNewRoute: AppContestsNewRoute,
  AppLocationsIdRoute: AppLocationsIdRouteWithChildren,
  AppMessagesIdRoute: AppMessagesIdRoute,
  AppProfileEditRoute: AppProfileEditRoute,
  AppProfileFollowRequestsRoute: AppProfileFollowRequestsRoute,
  AppStudentsIdRoute: AppStudentsIdRoute,
  AppStudentsImportRoute: AppStudentsImportRoute,
  AppStudentsNewRoute: AppStudentsNewRoute,
  AppSubscriptionsIdRoute: AppSubscriptionsIdRoute,
  AppSubscriptionsNewRoute: AppSubscriptionsNewRoute,
  AppTrainersNewRoute: AppTrainersNewRoute,
  AppBatchesIndexRoute: AppBatchesIndexRoute,
  AppBookingsIndexRoute: AppBookingsIndexRoute,
  AppCertificatesIndexRoute: AppCertificatesIndexRoute,
  AppContestsIndexRoute: AppContestsIndexRoute,
  AppLocationsIndexRoute: AppLocationsIndexRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
  AppStudentsIndexRoute: AppStudentsIndexRoute,
  AppSubscriptionsIndexRoute: AppSubscriptionsIndexRoute,
  AppTrainersIndexRoute: AppTrainersIndexRoute,
  AppLocationsIdClassesRoute: AppLocationsIdClassesRoute,
  AppSessionsIdAttendanceRoute: AppSessionsIdAttendanceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MeRouteChildren {
  MeAttendanceRoute: typeof MeAttendanceRoute
  MeBookRoute: typeof MeBookRoute
  MeBookingsRoute: typeof MeBookingsRoute
  MeCalendarRoute: typeof MeCalendarRoute
  MeCheckInRoute: typeof MeCheckInRoute
  MeContestsRoute: typeof MeContestsRoute
  MeFeedRoute: typeof MeFeedRoute
  MeInvoicesRoute: typeof MeInvoicesRoute
  MeOnboardingRoute: typeof MeOnboardingRoute
  MeProfileRoute: typeof MeProfileRoute
  MeSubscriptionsRoute: typeof MeSubscriptionsRoute
  MeIndexRoute: typeof MeIndexRoute
  MeBatchesIdRoute: typeof MeBatchesIdRoute
  MeLocationsIdRoute: typeof MeLocationsIdRoute
  MeMessagesIdRoute: typeof MeMessagesIdRoute
  MeProfileEditRoute: typeof MeProfileEditRoute
  MeProfileFollowRequestsRoute: typeof MeProfileFollowRequestsRoute
  MeLocationsIndexRoute: typeof MeLocationsIndexRoute
  MeMessagesIndexRoute: typeof MeMessagesIndexRoute
  MeTrainersIndexRoute: typeof MeTrainersIndexRoute
  MeLocationsIdClassesRoute: typeof MeLocationsIdClassesRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeAttendanceRoute: MeAttendanceRoute,
  MeBookRoute: MeBookRoute,
  MeBookingsRoute: MeBookingsRoute,
  MeCalendarRoute: MeCalendarRoute,
  MeCheckInRoute: MeCheckInRoute,
  MeContestsRoute: MeContestsRoute,
  MeFeedRoute: MeFeedRoute,
  MeInvoicesRoute: MeInvoicesRoute,
  MeOnboardingRoute: MeOnboardingRoute,
  MeProfileRoute: MeProfileRoute,
  MeSubscriptionsRoute: MeSubscriptionsRoute,
  MeIndexRoute: MeIndexRoute,
  MeBatchesIdRoute: MeBatchesIdRoute,
  MeLocationsIdRoute: MeLocationsIdRoute,
  MeMessagesIdRoute: MeMessagesIdRoute,
  MeProfileEditRoute: MeProfileEditRoute,
  MeProfileFollowRequestsRoute: MeProfileFollowRequestsRoute,
  MeLocationsIndexRoute: MeLocationsIndexRoute,
  MeMessagesIndexRoute: MeMessagesIndexRoute,
  MeTrainersIndexRoute: MeTrainersIndexRoute,
  MeLocationsIdClassesRoute: MeLocationsIdClassesRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MeRoute: MeRouteWithChildren,
  RegisterRoute: RegisterRoute,
  StudioRoute: StudioRoute,
  PostsIdRoute: PostsIdRoute,
  TrainersIdRoute: TrainersIdRoute,
  UsersIdRoute: UsersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
