"use client";

import {
  IconActivity,
  IconAlarmFilled,
  IconAlertCircleFilled,
  IconAlertOctagonFilled,
  IconAlertTriangleFilled,
  IconArchiveFilled,
  IconArrowDown,
  IconArrowLeft,
  IconArrowRight,
  IconArrowUp,
  IconArrowUpRight,
  IconBellFilled,
  IconBluetooth,
  IconBold,
  IconBoltFilled,
  IconBookFilled,
  IconBookmarkFilled,
  IconBuildingBank,
  IconBulbFilled,
  IconCalculatorFilled,
  IconCalendarFilled,
  IconCameraFilled,
  IconChartBar,
  IconChartLine,
  IconChartPieFilled,
  IconCheckFilled,
  IconChevronDownFilled,
  IconChevronLeft,
  IconChevronRightFilled,
  IconChevronUp,
  IconCircleCheckFilled,
  IconCircleDashed,
  IconCircleFilled,
  IconCircleXFilled,
  IconClipboardFilled,
  IconClockFilled,
  IconCloudFilled,
  IconCode,
  IconCopyFilled,
  IconCreditCardFilled,
  IconCut,
  IconDatabaseFilled,
  IconDeviceDesktopFilled,
  IconDeviceFloppyFilled,
  IconDeviceMobileFilled,
  IconDotsFilled,
  IconDotsVerticalFilled,
  IconDownloadFilled,
  IconEditFilled,
  IconExternalLinkFilled,
  IconEyeClosed,
  IconEyeFilled,
  IconFileCodeFilled,
  IconFileFilled,
  IconFileTextFilled,
  IconFilterPlus,
  IconFolderFilled,
  IconFolderOpenFilled,
  IconFolderPlus,
  IconGitBranch,
  IconGripVertical,
  IconHeartFilled,
  IconHelpCircleFilled,
  IconHomeFilled,
  IconInbox,
  IconInfoCircleFilled,
  IconItalic,
  IconKeyboardFilled,
  IconLanguage,
  IconLayoutFilled,
  IconLayoutGridFilled,
  IconLayoutSidebarFilled,
  IconLifebuoyFilled,
  IconLinkFilled,
  IconListFilled,
  IconLoader2,
  IconLockFilled,
  IconLockOpen,
  IconLogin,
  IconLogout,
  IconMailFilled,
  IconMap,
  IconMapPinFilled,
  IconMaximize,
  IconMenu,
  IconMessageFilled,
  IconMicrophoneFilled,
  IconMinimize,
  IconMinus,
  IconMoodSmileFilled,
  IconMoonFilled,
  IconPaletteFilled,
  IconPaperclip,
  IconPencilFilled,
  IconPhotoFilled,
  IconPinnedFilled,
  IconPlusFilled,
  IconRefresh,
  IconRobot,
  IconRosetteDiscountCheckFilled,
  IconRotateClockwise2,
  IconSearchFilled,
  IconSelector,
  IconSendFilled,
  IconServer,
  IconSettingsFilled,
  IconShare,
  IconShieldFilled,
  IconShoppingBag,
  IconShoppingCartFilled,
  IconSparklesFilled,
  IconSquarePlus,
  IconStarFilled,
  IconSunFilled,
  IconTableFilled,
  IconTagFilled,
  IconTerminal,
  IconTrashFilled,
  IconTrendingUp,
  IconUnderline,
  IconUpload,
  IconUserFilled,
  IconUsers,
  IconVolume,
  IconVolumeOff,
  IconWallet,
  IconWand,
  IconWifi,
  IconWorldFilled,
  IconXFilled,
  IconZoomInFilled,
  IconZoomOutFilled,
} from "@tabler/icons-react";
import type React from "react";

const pack = {
  id: "tabler-filled",
  icons: {
    activity: IconActivity,
    "alert-circle": IconAlertCircleFilled,
    "alert-octagon": IconAlertOctagonFilled,
    "alert-triangle": IconAlertTriangleFilled,
    archive: IconArchiveFilled,
    "arrow-down": IconArrowDown,
    "arrow-left": IconArrowLeft,
    "arrow-right": IconArrowRight,
    "arrow-up": IconArrowUp,
    "arrow-up-right": IconArrowUpRight,
    "badge-check": IconRosetteDiscountCheckFilled,
    bell: IconBellFilled,
    bluetooth: IconBluetooth,
    bold: IconBold,
    "book-open": IconBookFilled,
    bookmark: IconBookmarkFilled,
    bot: IconRobot,
    building: IconBuildingBank,
    calculator: IconCalculatorFilled,
    calendar: IconCalendarFilled,
    camera: IconCameraFilled,
    "chart-bar": IconChartBar,
    "chart-line": IconChartLine,
    "chart-pie": IconChartPieFilled,
    check: IconCheckFilled,
    "check-circle": IconCircleCheckFilled,
    "chevron-down": IconChevronDownFilled,
    "chevron-left": IconChevronLeft,
    "chevron-right": IconChevronRightFilled,
    "chevron-up": IconChevronUp,
    "chevrons-up-down": IconSelector,
    circle: IconCircleFilled,
    "circle-dashed": IconCircleDashed,
    clipboard: IconClipboardFilled,
    "clipboard-paste": IconClipboardFilled,
    clock: IconClockFilled,
    cloud: IconCloudFilled,
    code: IconCode,
    copy: IconCopyFilled,
    "credit-card": IconCreditCardFilled,
    database: IconDatabaseFilled,
    delete: IconTrashFilled,
    download: IconDownloadFilled,
    edit: IconPencilFilled,
    "external-link": IconExternalLinkFilled,
    eye: IconEyeFilled,
    "eye-off": IconEyeClosed,
    file: IconFileFilled,
    "file-code": IconFileCodeFilled,
    "file-text": IconFileTextFilled,
    filter: IconFilterPlus,
    folder: IconFolderFilled,
    "folder-open": IconFolderOpenFilled,
    "folder-plus": IconFolderPlus,
    "git-branch": IconGitBranch,
    globe: IconWorldFilled,
    "grip-vertical": IconGripVertical,
    heart: IconHeartFilled,
    "help-circle": IconHelpCircleFilled,
    home: IconHomeFilled,
    image: IconPhotoFilled,
    inbox: IconInbox,
    info: IconInfoCircleFilled,
    italic: IconItalic,
    keyboard: IconKeyboardFilled,
    languages: IconLanguage,
    layout: IconLayoutFilled,
    "layout-grid": IconLayoutGridFilled,
    "life-buoy": IconLifebuoyFilled,
    lightbulb: IconBulbFilled,
    link: IconLinkFilled,
    list: IconListFilled,
    loader: IconLoader2,
    lock: IconLockFilled,
    "log-in": IconLogin,
    "log-out": IconLogout,
    mail: IconMailFilled,
    map: IconMap,
    "map-pin": IconMapPinFilled,
    maximize: IconMaximize,
    menu: IconMenu,
    "message-square": IconMessageFilled,
    mic: IconMicrophoneFilled,
    minimize: IconMinimize,
    minus: IconMinus,
    monitor: IconDeviceDesktopFilled,
    moon: IconMoonFilled,
    "more-horizontal": IconDotsFilled,
    "more-vertical": IconDotsVerticalFilled,
    palette: IconPaletteFilled,
    "panel-left": IconLayoutSidebarFilled,
    paperclip: IconPaperclip,
    "pen-square": IconEditFilled,
    pin: IconPinnedFilled,
    plus: IconPlusFilled,
    "plus-square": IconSquarePlus,
    refresh: IconRefresh,
    "rotate-cw": IconRotateClockwise2,
    save: IconDeviceFloppyFilled,
    scissors: IconCut,
    search: IconSearchFilled,
    send: IconSendFilled,
    server: IconServer,
    settings: IconSettingsFilled,
    share: IconShare,
    shield: IconShieldFilled,
    "shopping-bag": IconShoppingBag,
    "shopping-cart": IconShoppingCartFilled,
    smartphone: IconDeviceMobileFilled,
    smile: IconMoodSmileFilled,
    sparkles: IconSparklesFilled,
    star: IconStarFilled,
    sun: IconSunFilled,
    table: IconTableFilled,
    tag: IconTagFilled,
    terminal: IconTerminal,
    timer: IconAlarmFilled,
    trash: IconTrashFilled,
    "trending-up": IconTrendingUp,
    underline: IconUnderline,
    unlock: IconLockOpen,
    upload: IconUpload,
    user: IconUserFilled,
    users: IconUsers,
    volume: IconVolume,
    "volume-off": IconVolumeOff,
    wallet: IconWallet,
    wand: IconWand,
    wifi: IconWifi,
    x: IconXFilled,
    "x-circle": IconCircleXFilled,
    zap: IconBoltFilled,
    "zoom-in": IconZoomInFilled,
    "zoom-out": IconZoomOutFilled,
  },
};

export default pack;
