import type { TokenVocabulary } from "../theme/types.js";
import { ref, val } from "./helpers.js";

export const DEFAULT_COMPONENTS = {
  "btn-radius": ref("radius-md", "component"),
  "btn-font-weight": ref("font-weight-medium", "component"),
  "btn-font-size": ref("font-size-sm", "component"),
  "btn-font-size-xs": ref("font-size-xs", "component"),
  "btn-font-size-sm": val("0.8125rem", "component"),
  "btn-line-height": ref("line-height-tight", "component"),
  "btn-shadow": ref("shadow-none", "component"),
  "btn-icon-size": ref("font-size-sm", "component"),
  "btn-icon-size-xs": ref("font-size-xs", "component"),
  "btn-icon-size-sm": ref("font-size-md", "component"),
  "btn-icon-size-lg": ref("font-size-md", "component"),
  "btn-spinner-border-width": val("2px", "component"),
  "btn-spinner-duration": val("0.6s", "component"),

  "badge-radius": ref("radius-md", "component"),
  "alert-radius": ref("radius-lg", "component"),
  "input-radius": ref("radius-md", "component"),
  "input-font-size": ref("font-size-sm", "component"),
  "input-line-height": ref("line-height-tight", "component"),
  "input-padding-inline": val("0.625rem", "component"),
  "input-focus-ring-width": val("2px", "component"),
  "input-shadow": ref("shadow-none", "component"),

  "select-radius": ref("input-radius", "component"),
  "select-font-size": ref("input-font-size", "component"),

  "card-radius": ref("radius-lg", "component"),
  "card-shadow": ref("shadow-sm", "component"),
  "card-background": ref("color-card", "component"),
  "popover-radius": ref("radius-md", "component"),
  "tooltip-radius": ref("radius-sm", "component"),
  "tooltip-padding": val("0.375rem 0.625rem", "component"),
  "tooltip-font-size": ref("font-size-xs", "component"),
  "tooltip-shadow": ref("shadow-md", "component"),

  "tag-radius": ref("radius-lg", "component"),
  "list-box-item-radius": ref("radius-sm", "component"),
  "checkbox-radius": val("4px", "component"),
  "checkbox-card-radius": ref("radius-lg", "component"),
  "radio-radius": ref("radius-full", "component"),
  "radio-card-radius": ref("radius-lg", "component"),
  "switch-radius": ref("radius-full", "component"),
  "switch-card-radius": ref("radius-lg", "component"),
  "avatar-radius": ref("radius-full", "component"),
  "color-area-radius": ref("radius-md", "component"),
  "color-swatch-picker-item-radius": ref("radius-md", "component"),
  "calendar-cell-radius": ref("radius-lg", "component"),
  "calendar-cell-size": val("2.25rem", "component"),
  "calendar-range-radius": ref("radius-sm", "component"),

  "dialog-radius": ref("radius-lg", "component"),
  "dialog-shadow": ref("shadow-lg", "component"),
  "dialog-padding": ref("space-6", "component"),

  "modal-backdrop-blur": ref("blur-sm", "component"),
  "modal-backdrop-opacity": val("40%", "component"),
  "modal-background": ref("color-bg", "component"),
  "modal-radius": ref("radius-lg", "component"),
  "modal-shadow": ref("shadow-lg", "component"),

  "table-border-color": ref("color-border", "component"),
  "table-header-background": ref("color-muted", "component"),
  "table-cell-padding": ref("space-3", "component"),
  "table-font-size": ref("font-size-sm", "component"),

  "slider-track-radius": ref("radius-full", "component"),
  "slider-thumb-radius": ref("radius-full", "component"),
  "slider-thumb-size": val("calc(var(--space-3) * 1)", "component"),
  "slider-thumb-shadow": ref("shadow-none", "component"),
  "slider-fill-color": ref("color-primary", "component"),
  "slider-cursor": ref("cursor-interactive", "component"),
  "slider-dragging-cursor": ref("cursor-interactive", "component"),
  "slider-size": ref("space-1", "component"),

  "progress-track-size": ref("space-1", "component"),
  "progress-track-radius": ref("radius-full", "component"),
  "progress-fill-color": ref("color-primary", "component"),
} satisfies TokenVocabulary;
