import type { TokenVocabulary } from "../theme/types.js";
import { ref, val } from "./helpers.js";

export const DEFAULT_COMPONENTS = {
  "btn-radius": ref("radius-md", "component"),
  "btn-font-weight": ref("font-weight-medium", "component"),
  "btn-font-size": ref("font-size-sm", "component"),
  "btn-font-size-xs": ref("font-size-xs", "component"),
  "btn-font-size-sm": val("0.8125rem", "component"),
  "btn-line-height": ref("line-height-tight", "component"),
  "btn-shadow": ref("shadow-none", "component"),
  "btn-pressed-shadow": ref("shadow-none", "component"),
  "btn-hover-background": ref("color-neutral-hover", "component"),
  "btn-hover-shadow": ref("shadow-none", "component"),
  "btn-selected-shadow": ref("shadow-none", "component"),
  "btn-surface-gradient": val("none", "component"),
  "btn-primary-surface-gradient": val("none", "component"),
  "btn-default-surface-gradient": val("none", "component"),
  "btn-border-color": val("transparent", "component"),
  "btn-border-width": ref("border-width", "component"),
  "btn-backdrop-blur": val("0px", "component"),
  "btn-default-background": ref("color-neutral", "component"),
  "btn-primary-background": ref("color-primary", "component"),
  "btn-primary-foreground": ref("color-fg-on-primary", "component"),
  "btn-icon-size": ref("font-size-sm", "component"),
  "btn-icon-size-xs": ref("font-size-xs", "component"),
  "btn-icon-size-sm": ref("font-size-md", "component"),
  "btn-icon-size-lg": ref("font-size-md", "component"),
  "btn-spinner-border-width": val("2px", "component"),
  "btn-spinner-duration": val("0.6s", "component"),
  "btn-hover-scale": val("1.02", "component"),
  "btn-press-scale": val("0.93", "component"),

  "disabled-background": ref("color-disabled", "component"),
  "disabled-foreground": ref("color-fg-disabled", "component"),
  "disabled-border-color": ref("color-border-disabled", "component"),
  "disabled-shadow": ref("shadow-none", "component"),

  "btn-disabled-background": ref("disabled-background", "component"),
  "btn-disabled-foreground": ref("disabled-foreground", "component"),
  "btn-disabled-border-color": ref("disabled-border-color", "component"),
  "btn-disabled-shadow": ref("disabled-shadow", "component"),
  "btn-primary-disabled-background": ref(
    "btn-disabled-background",
    "component",
  ),
  "btn-primary-disabled-foreground": ref(
    "color-fg-primary-disabled",
    "component",
  ),
  "btn-primary-disabled-border-color": ref(
    "btn-disabled-border-color",
    "component",
  ),
  "btn-primary-disabled-shadow": ref("btn-disabled-shadow", "component"),

  "badge-radius": ref("radius-md", "component"),
  "alert-radius": ref("radius-lg", "component"),
  "input-radius": ref("radius-md", "component"),
  "input-font-size": ref("font-size-sm", "component"),
  "input-line-height": ref("line-height-tight", "component"),
  "input-padding-inline": val("0.625rem", "component"),
  "input-focus-ring-width": val("2px", "component"),
  "input-shadow": ref("shadow-none", "component"),
  "input-background": ref("color-field", "component"),
  "input-border-color": ref("color-border-field", "component"),
  "input-backdrop-blur": val("0px", "component"),
  "input-surface-gradient": val("none", "component"),
  "input-disabled-background": ref("disabled-background", "component"),
  "input-disabled-foreground": ref("disabled-foreground", "component"),
  "input-disabled-border-color": ref("disabled-border-color", "component"),
  "input-disabled-shadow": ref("disabled-shadow", "component"),

  "surface-background": ref("color-bg", "component"),

  "select-radius": ref("input-radius", "component"),
  "select-font-size": ref("input-font-size", "component"),

  "card-radius": ref("radius-lg", "component"),
  "card-border-width": ref("border-width", "component"),
  "card-shadow": ref("shadow-sm", "component"),
  "card-background": ref("color-card", "component"),
  "card-surface-gradient": val("none", "component"),
  "card-backdrop-blur": val("0px", "component"),
  "card-border-color": ref("color-border", "component"),
  "popover-radius": ref("radius-md", "component"),
  "popover-background": ref("color-popover", "component"),
  "popover-border-color": ref("color-border", "component"),
  "popover-backdrop-blur": val("0px", "component"),
  "popover-shadow": val("0 4px 6px -1px rgb(0 0 0 / 10%)", "component"),
  "tooltip-radius": ref("radius-sm", "component"),
  "tooltip-padding": val("0.375rem 0.625rem", "component"),
  "tooltip-font-size": ref("font-size-xs", "component"),
  "tooltip-shadow": ref("shadow-md", "component"),

  "tag-radius": ref("radius-lg", "component"),
  "list-box-item-radius": ref("radius-sm", "component"),
  "checkbox-radius": val("4px", "component"),
  "checkbox-card-radius": ref("radius-lg", "component"),
  "radio-radius": ref("radius-full", "component"),
  "radio-card-radius": ref("radius-lg", "component"),
  "switch-radius": ref("radius-full", "component"),
  "switch-card-radius": ref("radius-lg", "component"),
  "switch-indicator-shadow": ref("shadow-none", "component"),
  "switch-thumb-shadow": ref("shadow-sm", "component"),
  "switch-indicator-background": ref("color-neutral", "component"),
  "switch-indicator-background-selected": ref("color-accent", "component"),
  "switch-indicator-surface-gradient": val("none", "component"),
  "switch-thumb-background": val("white", "component"),
  "switch-thumb-surface-gradient": val("none", "component"),
  "avatar-radius": ref("radius-full", "component"),
  "color-area-radius": ref("radius-md", "component"),
  "color-swatch-picker-item-radius": ref("radius-md", "component"),
  "calendar-cell-radius": ref("radius-lg", "component"),
  "calendar-cell-size": val("2.25rem", "component"),
  "calendar-range-radius": ref("radius-sm", "component"),

  "dialog-radius": ref("radius-lg", "component"),
  "dialog-shadow": ref("shadow-lg", "component"),
  "dialog-padding": ref("space-6", "component"),

  "modal-backdrop-blur": ref("blur-sm", "component"),
  "modal-backdrop-opacity": val("40%", "component"),
  "modal-background": ref("color-bg", "component"),
  "modal-radius": ref("radius-lg", "component"),
  "modal-shadow": ref("shadow-lg", "component"),
  "modal-border-color": ref("color-border", "component"),
  "modal-panel-backdrop-blur": val("0px", "component"),

  "table-border-color": ref("color-border", "component"),
  "table-header-background": ref("color-muted", "component"),
  "table-cell-padding": ref("space-3", "component"),
  "table-font-size": ref("font-size-sm", "component"),

  "slider-track-radius": ref("radius-full", "component"),
  "slider-thumb-radius": ref("radius-full", "component"),
  "slider-thumb-size": val("calc(var(--space-3) * 1)", "component"),
  "slider-thumb-shadow": ref("shadow-none", "component"),
  "slider-thumb-border-width": {
    target: {
      light: { value: "0px" },
      dark: { value: "1px" },
    },
    category: "component",
  },
  "slider-thumb-border-color": {
    target: {
      light: { value: "transparent" },
      dark: { ref: "color-border" },
    },
    category: "component",
  },
  "slider-track-background": ref("color-neutral", "component"),
  "slider-track-shadow": ref("shadow-none", "component"),
  "slider-thumb-background": ref("color-fg", "component"),
  "slider-fill-color": ref("color-primary", "component"),
  "slider-cursor": ref("cursor-interactive", "component"),
  "slider-dragging-cursor": ref("cursor-interactive", "component"),
  "slider-size": ref("space-1", "component"),

  "progress-track-size": ref("space-1", "component"),
  "progress-track-radius": ref("radius-full", "component"),
  "progress-fill-color": ref("color-primary", "component"),

  "scrollbar-size": val("10px", "component"),
  "scrollbar-width": val("thin", "component"),
  "scrollbar-track-background": val("transparent", "component"),
  "scrollbar-track-radius": ref("radius-full", "component"),
  "scrollbar-track-shadow": ref("shadow-none", "component"),
  "scrollbar-thumb-background": ref("color-neutral", "component"),
  "scrollbar-thumb-hover-background": ref("color-neutral-hover", "component"),
  "scrollbar-thumb-active-background": ref("color-neutral-active", "component"),
  "scrollbar-thumb-radius": ref("radius-full", "component"),
  "scrollbar-thumb-border-width": val("0px", "component"),
  "scrollbar-thumb-border-color": val("transparent", "component"),
  "scrollbar-thumb-shadow": ref("shadow-none", "component"),
  "scrollbar-thumb-hover-shadow": ref("shadow-none", "component"),
} satisfies TokenVocabulary;
